package com.pasantia.entidades;
// Generated 15/08/2013 10:50:14 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CargadosCsv generated by hbm2java
 */
@Entity
@Table(name="cargadosCSV"
    ,catalog="CasinoPasantia"
)
public class CargadosCsv  implements java.io.Serializable {


     private Integer idnewTable;
     private Integer divipola;
     private Integer codDepto;
     private Integer codMpio;
     private String dpto;
     private String nomMpio;
     private String nomPoblad;

    public CargadosCsv() {
    }

    public CargadosCsv(Integer divipola, Integer codDepto, Integer codMpio, String dpto, String nomMpio, String nomPoblad) {
       this.divipola = divipola;
       this.codDepto = codDepto;
       this.codMpio = codMpio;
       this.dpto = dpto;
       this.nomMpio = nomMpio;
       this.nomPoblad = nomPoblad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idnew_table", unique=true, nullable=false)
    public Integer getIdnewTable() {
        return this.idnewTable;
    }
    
    public void setIdnewTable(Integer idnewTable) {
        this.idnewTable = idnewTable;
    }
    
    @Column(name="DIVIPOLA")
    public Integer getDivipola() {
        return this.divipola;
    }
    
    public void setDivipola(Integer divipola) {
        this.divipola = divipola;
    }
    
    @Column(name="COD_DEPTO")
    public Integer getCodDepto() {
        return this.codDepto;
    }
    
    public void setCodDepto(Integer codDepto) {
        this.codDepto = codDepto;
    }
    
    @Column(name="COD_MPIO")
    public Integer getCodMpio() {
        return this.codMpio;
    }
    
    public void setCodMpio(Integer codMpio) {
        this.codMpio = codMpio;
    }
    
    @Column(name="DPTO")
    public String getDpto() {
        return this.dpto;
    }
    
    public void setDpto(String dpto) {
        this.dpto = dpto;
    }
    
    @Column(name="NOM_MPIO")
    public String getNomMpio() {
        return this.nomMpio;
    }
    
    public void setNomMpio(String nomMpio) {
        this.nomMpio = nomMpio;
    }
    
    @Column(name="NOM_POBLAD")
    public String getNomPoblad() {
        return this.nomPoblad;
    }
    
    public void setNomPoblad(String nomPoblad) {
        this.nomPoblad = nomPoblad;
    }




}


