package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {
    private static final long serialVersionUID = 5497764626250452242L;


     private Integer idCargo;
     private String descripcion;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public Cargo() {
    }

	
    public Cargo(String descripcion) {
        this.descripcion = descripcion;
    }
    public Cargo(String descripcion, Set<Persona> personas) {
       this.descripcion = descripcion;
       this.personas = personas;
    }
   
    public Integer getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(Integer idCargo) {
        this.idCargo = idCargo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


