package com.pasantia.entidades;
// Generated 3/09/2013 11:43:16 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name="Cargo"
    ,catalog="CasinoPasantia"
)
public class Cargo  implements java.io.Serializable {


     private Integer idCargo;
     private String descripcion;
     private Set personas = new HashSet(0);

    public Cargo() {
    }

	
    public Cargo(String descripcion) {
        this.descripcion = descripcion;
    }
    public Cargo(String descripcion, Set personas) {
       this.descripcion = descripcion;
       this.personas = personas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idCargo", unique=true, nullable=false)
    public Integer getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(Integer idCargo) {
        this.idCargo = idCargo;
    }
    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="cargo")
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


