package com.pasantia.entidades;
// Generated 10/09/2013 10:40:59 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Casino generated by hbm2java
 */
@Entity
@Table(name="Casino"
    ,catalog="CasinoPasantia"
)
public class Casino  implements java.io.Serializable {


     private Integer idCasino;
     private Persona persona;
     private Batallon batallon;
     private String nombre;
     private String nit;
     private String telefono1;
     private String telefono2;
     private Set productos = new HashSet(0);
     private Set tblcompras = new HashSet(0);
     private Set tblventas = new HashSet(0);

    public Casino() {
    }

	
    public Casino(Batallon batallon, String nombre, String nit, String telefono1) {
        this.batallon = batallon;
        this.nombre = nombre;
        this.nit = nit;
        this.telefono1 = telefono1;
    }
    public Casino(Persona persona, Batallon batallon, String nombre, String nit, String telefono1, String telefono2, Set productos, Set tblcompras, Set tblventas) {
       this.persona = persona;
       this.batallon = batallon;
       this.nombre = nombre;
       this.nit = nit;
       this.telefono1 = telefono1;
       this.telefono2 = telefono2;
       this.productos = productos;
       this.tblcompras = tblcompras;
       this.tblventas = tblventas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idCasino", unique=true, nullable=false)
    public Integer getIdCasino() {
        return this.idCasino;
    }
    
    public void setIdCasino(Integer idCasino) {
        this.idCasino = idCasino;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_persona")
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="secbatallon", nullable=false)
    public Batallon getBatallon() {
        return this.batallon;
    }
    
    public void setBatallon(Batallon batallon) {
        this.batallon = batallon;
    }
    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="nit", nullable=false, length=45)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    
    @Column(name="telefono 1", nullable=false, length=45)
    public String getTelefono1() {
        return this.telefono1;
    }
    
    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1;
    }
    
    @Column(name="telefono 2", length=45)
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="casino")
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="casino")
    public Set getTblcompras() {
        return this.tblcompras;
    }
    
    public void setTblcompras(Set tblcompras) {
        this.tblcompras = tblcompras;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="casino")
    public Set getTblventas() {
        return this.tblventas;
    }
    
    public void setTblventas(Set tblventas) {
        this.tblventas = tblventas;
    }




}


