package com.pasantia.entidades;
// Generated 6/10/2013 04:27:25 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatalogoVenta generated by hbm2java
 */
@Entity
@Table(name="Catalogo_Venta"
    ,catalog="CasinoPasantia"
)
public class CatalogoVenta  implements java.io.Serializable {


     private Integer idCatalogoVenta;
     private String descripcion;
     private Set personas = new HashSet(0);

    public CatalogoVenta() {
    }

	
    public CatalogoVenta(String descripcion) {
        this.descripcion = descripcion;
    }
    public CatalogoVenta(String descripcion, Set personas) {
       this.descripcion = descripcion;
       this.personas = personas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idCatalogo_Venta", unique=true, nullable=false)
    public Integer getIdCatalogoVenta() {
        return this.idCatalogoVenta;
    }
    
    public void setIdCatalogoVenta(Integer idCatalogoVenta) {
        this.idCatalogoVenta = idCatalogoVenta;
    }
    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="catalogoVenta")
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


