package com.pasantia.entidades;
// Generated 3/09/2013 11:43:16 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatalogoVenta generated by hbm2java
 */
@Entity
@Table(name="Catalogo_Venta"
    ,catalog="CasinoPasantia"
)
public class CatalogoVenta  implements java.io.Serializable {


     private Integer idCatalogoVenta;
     private DiasEntregaPedidos diasEntregaPedidos;
     private DiasPedidos diasPedidos;
     private String descripcion;
     private Set personas = new HashSet(0);

    public CatalogoVenta() {
    }

	
    public CatalogoVenta(DiasEntregaPedidos diasEntregaPedidos, DiasPedidos diasPedidos, String descripcion) {
        this.diasEntregaPedidos = diasEntregaPedidos;
        this.diasPedidos = diasPedidos;
        this.descripcion = descripcion;
    }
    public CatalogoVenta(DiasEntregaPedidos diasEntregaPedidos, DiasPedidos diasPedidos, String descripcion, Set personas) {
       this.diasEntregaPedidos = diasEntregaPedidos;
       this.diasPedidos = diasPedidos;
       this.descripcion = descripcion;
       this.personas = personas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idCatalogo_Venta", unique=true, nullable=false)
    public Integer getIdCatalogoVenta() {
        return this.idCatalogoVenta;
    }
    
    public void setIdCatalogoVenta(Integer idCatalogoVenta) {
        this.idCatalogoVenta = idCatalogoVenta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_ds_entrega", nullable=false)
    public DiasEntregaPedidos getDiasEntregaPedidos() {
        return this.diasEntregaPedidos;
    }
    
    public void setDiasEntregaPedidos(DiasEntregaPedidos diasEntregaPedidos) {
        this.diasEntregaPedidos = diasEntregaPedidos;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_ds_pedido", nullable=false)
    public DiasPedidos getDiasPedidos() {
        return this.diasPedidos;
    }
    
    public void setDiasPedidos(DiasPedidos diasPedidos) {
        this.diasPedidos = diasPedidos;
    }
    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="catalogoVenta")
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


