package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {
    private static final long serialVersionUID = -5901472433135034976L;


     private Integer idCiudad;
     private Departamento departamento;
     private String nombreCiudad;
     private Double latitud;
     private Double longitud;
     private Set<Tblproveedor> tblproveedors = new HashSet<Tblproveedor>(0);
     private Set<Persona> personas = new HashSet<Persona>(0);
     private Set<Batallon> batallons = new HashSet<Batallon>(0);

    public Ciudad() {
    }

	
    public Ciudad(Departamento departamento, String nombreCiudad) {
        this.departamento = departamento;
        this.nombreCiudad = nombreCiudad;
    }
    public Ciudad(Departamento departamento, String nombreCiudad, Double latitud, Double longitud, Set<Tblproveedor> tblproveedors, Set<Persona> personas, Set<Batallon> batallons) {
       this.departamento = departamento;
       this.nombreCiudad = nombreCiudad;
       this.latitud = latitud;
       this.longitud = longitud;
       this.tblproveedors = tblproveedors;
       this.personas = personas;
       this.batallons = batallons;
    }
   
    public Integer getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(Integer idCiudad) {
        this.idCiudad = idCiudad;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombreCiudad() {
        return this.nombreCiudad;
    }
    
    public void setNombreCiudad(String nombreCiudad) {
        this.nombreCiudad = nombreCiudad;
    }
    public Double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }
    public Double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }
    public Set<Tblproveedor> getTblproveedors() {
        return this.tblproveedors;
    }
    
    public void setTblproveedors(Set<Tblproveedor> tblproveedors) {
        this.tblproveedors = tblproveedors;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }
    public Set<Batallon> getBatallons() {
        return this.batallons;
    }
    
    public void setBatallons(Set<Batallon> batallons) {
        this.batallons = batallons;
    }




}


