package com.pasantia.entidades;
// Generated 23/09/2013 01:53:37 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CiudadesColombia generated by hbm2java
 */
@Entity
@Table(name="CiudadesColombia"
    ,catalog="CasinoPasantia"
)
public class CiudadesColombia  implements java.io.Serializable {


     private int idCiudadesColombia;
     private String ciudad;
     private Double latitud;
     private Double longitud;

    public CiudadesColombia() {
    }

	
    public CiudadesColombia(int idCiudadesColombia) {
        this.idCiudadesColombia = idCiudadesColombia;
    }
    public CiudadesColombia(int idCiudadesColombia, String ciudad, Double latitud, Double longitud) {
       this.idCiudadesColombia = idCiudadesColombia;
       this.ciudad = ciudad;
       this.latitud = latitud;
       this.longitud = longitud;
    }
   
     @Id 
    
    @Column(name="idCiudadesColombia", unique=true, nullable=false)
    public int getIdCiudadesColombia() {
        return this.idCiudadesColombia;
    }
    
    public void setIdCiudadesColombia(int idCiudadesColombia) {
        this.idCiudadesColombia = idCiudadesColombia;
    }
    
    @Column(name="Ciudad", length=300)
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    
    @Column(name="latitud", precision=22, scale=0)
    public Double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }
    
    @Column(name="longitud", precision=22, scale=0)
    public Double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }




}


