package com.pasantia.entidades;
// Generated 17/08/2013 10:58:34 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name="Compra"
    ,catalog="CasinoPasantia"
)
public class Compra  implements java.io.Serializable {


     private Integer idCompra;
     private FechaEntrega fechaEntrega;
     private FechaCompra fechaCompra;
     private Proveedor proveedor;

    public Compra() {
    }

    public Compra(FechaEntrega fechaEntrega, FechaCompra fechaCompra, Proveedor proveedor) {
       this.fechaEntrega = fechaEntrega;
       this.fechaCompra = fechaCompra;
       this.proveedor = proveedor;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idCompra", unique=true, nullable=false)
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_fecha_entrega", nullable=false)
    public FechaEntrega getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(FechaEntrega fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_fecha_compra", nullable=false)
    public FechaCompra getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(FechaCompra fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_proveedor", nullable=false)
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }




}


