package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA



/**
 * CoordenadasCiudad generated by hbm2java
 */
public class CoordenadasCiudad  implements java.io.Serializable {
    private static final long serialVersionUID = 2188427229284130874L;


     private int idCoordenadasCiudad;
     private String nombreCiudad;
     private Double latitud;
     private Double longitud;

    public CoordenadasCiudad() {
    }

	
    public CoordenadasCiudad(int idCoordenadasCiudad) {
        this.idCoordenadasCiudad = idCoordenadasCiudad;
    }
    public CoordenadasCiudad(int idCoordenadasCiudad, String nombreCiudad, Double latitud, Double longitud) {
       this.idCoordenadasCiudad = idCoordenadasCiudad;
       this.nombreCiudad = nombreCiudad;
       this.latitud = latitud;
       this.longitud = longitud;
    }
   
    public int getIdCoordenadasCiudad() {
        return this.idCoordenadasCiudad;
    }
    
    public void setIdCoordenadasCiudad(int idCoordenadasCiudad) {
        this.idCoordenadasCiudad = idCoordenadasCiudad;
    }
    public String getNombreCiudad() {
        return this.nombreCiudad;
    }
    
    public void setNombreCiudad(String nombreCiudad) {
        this.nombreCiudad = nombreCiudad;
    }
    public Double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }
    public Double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }




}


