package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {
    private static final long serialVersionUID = -4384494624517397095L;


     private int idDepartamento;
     private Pais pais;
     private String nombreDepartamento;
     private Double longitud;
     private Double latitud;
     private Set<DivisionesUbicacion> divisionesUbicacions = new HashSet<DivisionesUbicacion>(0);
     private Set<Ciudad> ciudads = new HashSet<Ciudad>(0);

    public Departamento() {
    }

	
    public Departamento(int idDepartamento, Pais pais, String nombreDepartamento) {
        this.idDepartamento = idDepartamento;
        this.pais = pais;
        this.nombreDepartamento = nombreDepartamento;
    }
    public Departamento(int idDepartamento, Pais pais, String nombreDepartamento, Double longitud, Double latitud, Set<DivisionesUbicacion> divisionesUbicacions, Set<Ciudad> ciudads) {
       this.idDepartamento = idDepartamento;
       this.pais = pais;
       this.nombreDepartamento = nombreDepartamento;
       this.longitud = longitud;
       this.latitud = latitud;
       this.divisionesUbicacions = divisionesUbicacions;
       this.ciudads = ciudads;
    }
   
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public Double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }
    public Double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }
    public Set<DivisionesUbicacion> getDivisionesUbicacions() {
        return this.divisionesUbicacions;
    }
    
    public void setDivisionesUbicacions(Set<DivisionesUbicacion> divisionesUbicacions) {
        this.divisionesUbicacions = divisionesUbicacions;
    }
    public Set<Ciudad> getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set<Ciudad> ciudads) {
        this.ciudads = ciudads;
    }




}


