package com.pasantia.entidades;
// Generated 3/09/2013 11:43:16 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DetalleVenta generated by hbm2java
 */
@Entity
@Table(name="Detalle_Venta"
    ,catalog="CasinoPasantia"
)
public class DetalleVenta  implements java.io.Serializable {


     private Integer idDetalleVenta;
     private Producto producto;
     private FormaDePagar formaDePagar;
     private int cantidad;
     private long iva;
     private Long subtotal;
     private Long total;
     private Set ventas = new HashSet(0);
     private Set inventarios = new HashSet(0);

    public DetalleVenta() {
    }

	
    public DetalleVenta(Producto producto, FormaDePagar formaDePagar, int cantidad, long iva) {
        this.producto = producto;
        this.formaDePagar = formaDePagar;
        this.cantidad = cantidad;
        this.iva = iva;
    }
    public DetalleVenta(Producto producto, FormaDePagar formaDePagar, int cantidad, long iva, Long subtotal, Long total, Set ventas, Set inventarios) {
       this.producto = producto;
       this.formaDePagar = formaDePagar;
       this.cantidad = cantidad;
       this.iva = iva;
       this.subtotal = subtotal;
       this.total = total;
       this.ventas = ventas;
       this.inventarios = inventarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idDetalle_Venta", unique=true, nullable=false)
    public Integer getIdDetalleVenta() {
        return this.idDetalleVenta;
    }
    
    public void setIdDetalleVenta(Integer idDetalleVenta) {
        this.idDetalleVenta = idDetalleVenta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_producto", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_forma_pago", nullable=false)
    public FormaDePagar getFormaDePagar() {
        return this.formaDePagar;
    }
    
    public void setFormaDePagar(FormaDePagar formaDePagar) {
        this.formaDePagar = formaDePagar;
    }
    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    
    @Column(name="iva", nullable=false, precision=10, scale=0)
    public long getIva() {
        return this.iva;
    }
    
    public void setIva(long iva) {
        this.iva = iva;
    }
    
    @Column(name="subtotal", precision=10, scale=0)
    public Long getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Long subtotal) {
        this.subtotal = subtotal;
    }
    
    @Column(name="total", precision=10, scale=0)
    public Long getTotal() {
        return this.total;
    }
    
    public void setTotal(Long total) {
        this.total = total;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detalleVenta")
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detalleVenta")
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }




}


