package com.pasantia.entidades;
// Generated 3/09/2013 11:43:16 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DetalleCompra generated by hbm2java
 */
@Entity
@Table(name="Detalle_Compra"
    ,catalog="CasinoPasantia"
)
public class DetalleCompra  implements java.io.Serializable {


     private Integer idDetalleCompra;
     private Proveedor proveedor;
     private Producto producto;
     private int cantidad;
     private long iva;
     private Long subtotal;
     private Long total;
     private Set inventarios = new HashSet(0);

    public DetalleCompra() {
    }

	
    public DetalleCompra(Proveedor proveedor, Producto producto, int cantidad, long iva) {
        this.proveedor = proveedor;
        this.producto = producto;
        this.cantidad = cantidad;
        this.iva = iva;
    }
    public DetalleCompra(Proveedor proveedor, Producto producto, int cantidad, long iva, Long subtotal, Long total, Set inventarios) {
       this.proveedor = proveedor;
       this.producto = producto;
       this.cantidad = cantidad;
       this.iva = iva;
       this.subtotal = subtotal;
       this.total = total;
       this.inventarios = inventarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idDetalle_Compra", unique=true, nullable=false)
    public Integer getIdDetalleCompra() {
        return this.idDetalleCompra;
    }
    
    public void setIdDetalleCompra(Integer idDetalleCompra) {
        this.idDetalleCompra = idDetalleCompra;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_proveedores", nullable=false)
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_productos", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    
    @Column(name="iva", nullable=false, precision=10, scale=0)
    public long getIva() {
        return this.iva;
    }
    
    public void setIva(long iva) {
        this.iva = iva;
    }
    
    @Column(name="subtotal", precision=10, scale=0)
    public Long getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Long subtotal) {
        this.subtotal = subtotal;
    }
    
    @Column(name="total", precision=10, scale=0)
    public Long getTotal() {
        return this.total;
    }
    
    public void setTotal(Long total) {
        this.total = total;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detalleCompra")
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }




}


