package com.pasantia.entidades;
// Generated 17/08/2013 10:58:34 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DiasEntregaPedidos generated by hbm2java
 */
@Entity
@Table(name="Dias_Entrega_Pedidos"
    ,catalog="CasinoPasantia"
)
public class DiasEntregaPedidos  implements java.io.Serializable {


     private Integer idDiasEntregaPedidos;
     private int lunes;
     private int martes;
     private int miercoles;
     private int jueves;
     private int viernes;
     private int sabado;
     private int domingo;
     private Set catalogoVentas = new HashSet(0);

    public DiasEntregaPedidos() {
    }

	
    public DiasEntregaPedidos(int lunes, int martes, int miercoles, int jueves, int viernes, int sabado, int domingo) {
        this.lunes = lunes;
        this.martes = martes;
        this.miercoles = miercoles;
        this.jueves = jueves;
        this.viernes = viernes;
        this.sabado = sabado;
        this.domingo = domingo;
    }
    public DiasEntregaPedidos(int lunes, int martes, int miercoles, int jueves, int viernes, int sabado, int domingo, Set catalogoVentas) {
       this.lunes = lunes;
       this.martes = martes;
       this.miercoles = miercoles;
       this.jueves = jueves;
       this.viernes = viernes;
       this.sabado = sabado;
       this.domingo = domingo;
       this.catalogoVentas = catalogoVentas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idDias_Entrega_Pedidos", unique=true, nullable=false)
    public Integer getIdDiasEntregaPedidos() {
        return this.idDiasEntregaPedidos;
    }
    
    public void setIdDiasEntregaPedidos(Integer idDiasEntregaPedidos) {
        this.idDiasEntregaPedidos = idDiasEntregaPedidos;
    }
    
    @Column(name="lunes", nullable=false)
    public int getLunes() {
        return this.lunes;
    }
    
    public void setLunes(int lunes) {
        this.lunes = lunes;
    }
    
    @Column(name="martes", nullable=false)
    public int getMartes() {
        return this.martes;
    }
    
    public void setMartes(int martes) {
        this.martes = martes;
    }
    
    @Column(name="miercoles", nullable=false)
    public int getMiercoles() {
        return this.miercoles;
    }
    
    public void setMiercoles(int miercoles) {
        this.miercoles = miercoles;
    }
    
    @Column(name="jueves", nullable=false)
    public int getJueves() {
        return this.jueves;
    }
    
    public void setJueves(int jueves) {
        this.jueves = jueves;
    }
    
    @Column(name="viernes", nullable=false)
    public int getViernes() {
        return this.viernes;
    }
    
    public void setViernes(int viernes) {
        this.viernes = viernes;
    }
    
    @Column(name="sabado", nullable=false)
    public int getSabado() {
        return this.sabado;
    }
    
    public void setSabado(int sabado) {
        this.sabado = sabado;
    }
    
    @Column(name="domingo", nullable=false)
    public int getDomingo() {
        return this.domingo;
    }
    
    public void setDomingo(int domingo) {
        this.domingo = domingo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="diasEntregaPedidos")
    public Set getCatalogoVentas() {
        return this.catalogoVentas;
    }
    
    public void setCatalogoVentas(Set catalogoVentas) {
        this.catalogoVentas = catalogoVentas;
    }




}


