package com.pasantia.entidades;
// Generated 10/09/2013 10:40:59 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Divisiones generated by hbm2java
 */
@Entity
@Table(name="Divisiones"
    ,catalog="CasinoPasantia"
)
public class Divisiones  implements java.io.Serializable {


     private Integer idDivisiones;
     private String nombreDivision;
     private Set batallons = new HashSet(0);
     private Set divisionesUbicacions = new HashSet(0);

    public Divisiones() {
    }

	
    public Divisiones(String nombreDivision) {
        this.nombreDivision = nombreDivision;
    }
    public Divisiones(String nombreDivision, Set batallons, Set divisionesUbicacions) {
       this.nombreDivision = nombreDivision;
       this.batallons = batallons;
       this.divisionesUbicacions = divisionesUbicacions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idDivisiones", unique=true, nullable=false)
    public Integer getIdDivisiones() {
        return this.idDivisiones;
    }
    
    public void setIdDivisiones(Integer idDivisiones) {
        this.idDivisiones = idDivisiones;
    }
    
    @Column(name="nombre_division", nullable=false)
    public String getNombreDivision() {
        return this.nombreDivision;
    }
    
    public void setNombreDivision(String nombreDivision) {
        this.nombreDivision = nombreDivision;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="divisiones")
    public Set getBatallons() {
        return this.batallons;
    }
    
    public void setBatallons(Set batallons) {
        this.batallons = batallons;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="divisiones")
    public Set getDivisionesUbicacions() {
        return this.divisionesUbicacions;
    }
    
    public void setDivisionesUbicacions(Set divisionesUbicacions) {
        this.divisionesUbicacions = divisionesUbicacions;
    }




}


