package com.pasantia.entidades;
// Generated 17/08/2013 10:58:34 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FechaEntrega generated by hbm2java
 */
@Entity
@Table(name="Fecha_Entrega"
    ,catalog="CasinoPasantia"
)
public class FechaEntrega  implements java.io.Serializable {


     private Integer idFechaEntrega;
     private Date fecha;
     private Set compras = new HashSet(0);

    public FechaEntrega() {
    }

	
    public FechaEntrega(Date fecha) {
        this.fecha = fecha;
    }
    public FechaEntrega(Date fecha, Set compras) {
       this.fecha = fecha;
       this.compras = compras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idFecha_Entrega", unique=true, nullable=false)
    public Integer getIdFechaEntrega() {
        return this.idFechaEntrega;
    }
    
    public void setIdFechaEntrega(Integer idFechaEntrega) {
        this.idFechaEntrega = idFechaEntrega;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="fechaEntrega")
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


