package com.pasantia.entidades;
// Generated 23/09/2013 01:53:37 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Imagen generated by hbm2java
 */
@Entity
@Table(name="Imagen"
    ,catalog="CasinoPasantia"
)
public class Imagen  implements java.io.Serializable {


     private Integer secimagen;
     private String direccion;
     private String titulo;
     private String descripcion;
     private boolean principal;

    public Imagen() {
    }

    public Imagen(String direccion, String titulo, String descripcion, boolean principal) {
       this.direccion = direccion;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.principal = principal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="secimagen", unique=true, nullable=false)
    public Integer getSecimagen() {
        return this.secimagen;
    }
    
    public void setSecimagen(Integer secimagen) {
        this.secimagen = secimagen;
    }
    
    @Column(name="direccion", nullable=false, length=100)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="titulo", nullable=false, length=100)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    
    @Column(name="descripcion", nullable=false, length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="principal", nullable=false)
    public boolean isPrincipal() {
        return this.principal;
    }
    
    public void setPrincipal(boolean principal) {
        this.principal = principal;
    }




}


