package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA



/**
 * Imagen generated by hbm2java
 */
public class Imagen  implements java.io.Serializable {
    private static final long serialVersionUID = -1143383470288118748L;


     private Integer secimagen;
     private String direccion;
     private String titulo;
     private String descripcion;
     private boolean principal;

    public Imagen() {
    }

    public Imagen(String direccion, String titulo, String descripcion, boolean principal) {
       this.direccion = direccion;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.principal = principal;
    }
   
    public Integer getSecimagen() {
        return this.secimagen;
    }
    
    public void setSecimagen(Integer secimagen) {
        this.secimagen = secimagen;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isPrincipal() {
        return this.principal;
    }
    
    public void setPrincipal(boolean principal) {
        this.principal = principal;
    }




}


