package com.pasantia.entidades;
// Generated 23/09/2013 01:53:37 PM by Hibernate Tools 3.2.1.GA


import com.pasantia.utilidades.UtilidadFecha;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="Persona"
    ,catalog="CasinoPasantia"
    , uniqueConstraints = @UniqueConstraint(columnNames="CEDULA") 
)
public class Persona  implements java.io.Serializable {


     @Id
     @GeneratedValue(strategy=IDENTITY)
     @Column(name="idTBLPERSONA", unique=true, nullable=false)
     private Integer idTblpersona;
     @ManyToOne(fetch=FetchType.LAZY)
     @JoinColumn(name="SECCATALOGO_VENTA")
     private CatalogoVenta catalogoVenta;
     @ManyToOne(fetch=FetchType.LAZY)
     @JoinColumn(name="SECCARGO")
     private Cargo cargo;
     @ManyToOne(fetch=FetchType.LAZY)
     @JoinColumn(name="SECCIUDAD", nullable=false)
     private Ciudad ciudad;
     @ManyToOne(fetch=FetchType.LAZY)
     @JoinColumn(name="SECTIPO_IDENTIFICACION", nullable=false)
     private TipoIdentificacion tipoIdentificacion;
     @ManyToOne(fetch=FetchType.LAZY)
     @JoinColumn(name="SECSEXO", nullable=false)
     private Sexo sexo;
     @ManyToOne(fetch=FetchType.LAZY)
     @JoinColumn(name="SECTIPO_PERSONA", nullable=false)
     private TipoPersona tipoPersona;
     @Column(name="PNOMBRE", nullable=false, length=45)
     private String pnombre;
     @Column(name="SNOMBRE", length=45)
     private String snombre;
     @Column(name="PAPELLIDO", nullable=false, length=45)
     private String papellido;
     @Column(name="SAPELLIDO", length=45)
     private String sapellido;
     @Column(name="CEDULA", unique=true, nullable=false, length=45)
     private String cedula;
     @Temporal(TemporalType.DATE)
     @Column(name="FECHA_NACIMIENTO", nullable=false, length=10)
     private Date fechaNacimiento;
     @Column(name="EMAIL", length=45)
     private String email;
     @Column(name="TELEFONO", length=45)
     private String telefono;
     @Column(name="MOVIL", length=45)
     private String movil;
     @Column(name="FOTO")
     private String foto;
     @Column(name="DIRECCION", nullable=false, length=45)
     private String direccion;
     @Column(name="BARRIO", nullable=false, length=45)
     private String barrio;
     @Column(name="LATITUD", nullable=false, precision=22, scale=0)
     private double latitud;
     @Column(name="LONGITUD", nullable=false, precision=22, scale=0)
     private double longitud;
     @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="personaBySecvendedor")
     private Set tblventasForSecvendedor = new HashSet(0);
     @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="persona")
     private Set batallons = new HashSet(0);
     @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="persona")
     private Set usuarios = new HashSet(0);
     @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="persona")
     private Set tblpedidos = new HashSet(0);
     @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="personaBySeccliente")
     private Set tblventasForSeccliente = new HashSet(0);
     @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="persona")
     private Set casinos = new HashSet(0);
     
     @Transient
     private Integer edad;

    public Persona() {
    }

	
    public Persona(Ciudad ciudad, TipoIdentificacion tipoIdentificacion, Sexo sexo, TipoPersona tipoPersona, String pnombre, String papellido, String cedula, Date fechaNacimiento, String direccion, String barrio, double latitud, double longitud) {
        this.ciudad = ciudad;
        this.tipoIdentificacion = tipoIdentificacion;
        this.sexo = sexo;
        this.tipoPersona = tipoPersona;
        this.pnombre = pnombre;
        this.papellido = papellido;
        this.cedula = cedula;
        this.fechaNacimiento = fechaNacimiento;
        this.direccion = direccion;
        this.barrio = barrio;
        this.latitud = latitud;
        this.longitud = longitud;
    }
    public Persona(CatalogoVenta catalogoVenta, Cargo cargo, Ciudad ciudad, TipoIdentificacion tipoIdentificacion, Sexo sexo, TipoPersona tipoPersona, String pnombre, String snombre, String papellido, String sapellido, String cedula, Date fechaNacimiento, String email, String telefono, String movil, String foto, String direccion, String barrio, double latitud, double longitud, Set tblventasForSecvendedor, Set batallons, Set usuarios, Set tblpedidos, Set tblventasForSeccliente, Set casinos) {
       this.catalogoVenta = catalogoVenta;
       this.cargo = cargo;
       this.ciudad = ciudad;
       this.tipoIdentificacion = tipoIdentificacion;
       this.sexo = sexo;
       this.tipoPersona = tipoPersona;
       this.pnombre = pnombre;
       this.snombre = snombre;
       this.papellido = papellido;
       this.sapellido = sapellido;
       this.cedula = cedula;
       this.fechaNacimiento = fechaNacimiento;
       this.email = email;
       this.telefono = telefono;
       this.movil = movil;
       this.foto = foto;
       this.direccion = direccion;
       this.barrio = barrio;
       this.latitud = latitud;
       this.longitud = longitud;
       this.tblventasForSecvendedor = tblventasForSecvendedor;
       this.batallons = batallons;
       this.usuarios = usuarios;
       this.tblpedidos = tblpedidos;
       this.tblventasForSeccliente = tblventasForSeccliente;
       this.casinos = casinos;
    }
   
         public Integer getIdTblpersona() {
        return this.idTblpersona;
    }
    
    public void setIdTblpersona(Integer idTblpersona) {
        this.idTblpersona = idTblpersona;
    }
    public CatalogoVenta getCatalogoVenta() {
        return this.catalogoVenta;
    }
    
    public void setCatalogoVenta(CatalogoVenta catalogoVenta) {
        this.catalogoVenta = catalogoVenta;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public TipoIdentificacion getTipoIdentificacion() {
        return this.tipoIdentificacion;
    }
    
    public void setTipoIdentificacion(TipoIdentificacion tipoIdentificacion) {
        this.tipoIdentificacion = tipoIdentificacion;
    }
    public Sexo getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Sexo sexo) {
        this.sexo = sexo;
    }
    public TipoPersona getTipoPersona() {
        return this.tipoPersona;
    }
    
    public void setTipoPersona(TipoPersona tipoPersona) {
        this.tipoPersona = tipoPersona;
    }
    
        public String getPnombre() {
        return this.pnombre;
    }
    
    public void setPnombre(String pnombre) {
        this.pnombre = pnombre;
    }
    
        public String getSnombre() {
        return this.snombre;
    }
    
    public void setSnombre(String snombre) {
        this.snombre = snombre;
    }
    
        public String getPapellido() {
        return this.papellido;
    }
    
    public void setPapellido(String papellido) {
        this.papellido = papellido;
    }
    
        public String getSapellido() {
        return this.sapellido;
    }
    
    public void setSapellido(String sapellido) {
        this.sapellido = sapellido;
    }
    
        public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
        public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    
        public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
        public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
        public String getMovil() {
        return this.movil;
    }
    
    public void setMovil(String movil) {
        this.movil = movil;
    }
    
        public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    
        public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
        public String getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(String barrio) {
        this.barrio = barrio;
    }
    
        public double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(double latitud) {
        this.latitud = latitud;
    }
    
        public double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(double longitud) {
        this.longitud = longitud;
    }
    public Set getTblventasForSecvendedor() {
        return this.tblventasForSecvendedor;
    }
    
    public void setTblventasForSecvendedor(Set tblventasForSecvendedor) {
        this.tblventasForSecvendedor = tblventasForSecvendedor;
    }
    public Set getBatallons() {
        return this.batallons;
    }
    
    public void setBatallons(Set batallons) {
        this.batallons = batallons;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getTblpedidos() {
        return this.tblpedidos;
    }
    
    public void setTblpedidos(Set tblpedidos) {
        this.tblpedidos = tblpedidos;
    }
    public Set getTblventasForSeccliente() {
        return this.tblventasForSeccliente;
    }
    
    public void setTblventasForSeccliente(Set tblventasForSeccliente) {
        this.tblventasForSeccliente = tblventasForSeccliente;
    }
    public Set getCasinos() {
        return this.casinos;
    }
    
    public void setCasinos(Set casinos) {
        this.casinos = casinos;
    }

    public Integer getEdad() {  
        if(this.fechaNacimiento!=null){
            edad=UtilidadFecha.calcularEdad(UtilidadFecha.
                    obtenerFechaEnFormatoTexto(this.fechaNacimiento, "dd/MM/yyyy"));
        }else{
            edad=0;
        }
        return edad;
    }

    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    
    




}


