package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PrecioCompra generated by hbm2java
 */
public class PrecioCompra  implements java.io.Serializable {
    private static final long serialVersionUID = -4298761930942256101L;


     private Integer idPrecioCompra;
     private Producto producto;
     private Date fecha;
     private long precio;
     private Boolean activo;

    public PrecioCompra() {
    }

	
    public PrecioCompra(Producto producto, Date fecha, long precio) {
        this.producto = producto;
        this.fecha = fecha;
        this.precio = precio;
    }
    public PrecioCompra(Producto producto, Date fecha, long precio, Boolean activo) {
       this.producto = producto;
       this.fecha = fecha;
       this.precio = precio;
       this.activo = activo;
    }
   
    public Integer getIdPrecioCompra() {
        return this.idPrecioCompra;
    }
    
    public void setIdPrecioCompra(Integer idPrecioCompra) {
        this.idPrecioCompra = idPrecioCompra;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public long getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(long precio) {
        this.precio = precio;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }




}


