package com.pasantia.entidades;
// Generated 23/09/2013 01:53:37 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrecioCompra generated by hbm2java
 */
@Entity
@Table(name="Precio_Compra"
    ,catalog="CasinoPasantia"
)
public class PrecioCompra  implements java.io.Serializable {


     private Integer idPrecioCompra;
     private Date fecha;
     private long precio;
     private Boolean activo;
     private Set productos = new HashSet(0);

    public PrecioCompra() {
    }

	
    public PrecioCompra(Date fecha, long precio) {
        this.fecha = fecha;
        this.precio = precio;
    }
    public PrecioCompra(Date fecha, long precio, Boolean activo, Set productos) {
       this.fecha = fecha;
       this.precio = precio;
       this.activo = activo;
       this.productos = productos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idPrecio_Compra", unique=true, nullable=false)
    public Integer getIdPrecioCompra() {
        return this.idPrecioCompra;
    }
    
    public void setIdPrecioCompra(Integer idPrecioCompra) {
        this.idPrecioCompra = idPrecioCompra;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="precio", nullable=false, precision=10, scale=0)
    public long getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(long precio) {
        this.precio = precio;
    }
    
    @Column(name="activo")
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="precioCompra")
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


