package com.pasantia.entidades;
// Generated 6/10/2013 04:27:25 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrecioCompra generated by hbm2java
 */
@Entity
@Table(name="Precio_Compra"
    ,catalog="CasinoPasantia"
)
public class PrecioCompra  implements java.io.Serializable {


     private Integer idPrecioCompra;
     private Producto producto;
     private Date fecha;
     private long precio;
     private Boolean activo;

    public PrecioCompra() {
    }

	
    public PrecioCompra(Producto producto, Date fecha, long precio) {
        this.producto = producto;
        this.fecha = fecha;
        this.precio = precio;
    }
    public PrecioCompra(Producto producto, Date fecha, long precio, Boolean activo) {
       this.producto = producto;
       this.fecha = fecha;
       this.precio = precio;
       this.activo = activo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idPrecio_Compra", unique=true, nullable=false)
    public Integer getIdPrecioCompra() {
        return this.idPrecioCompra;
    }
    
    public void setIdPrecioCompra(Integer idPrecioCompra) {
        this.idPrecioCompra = idPrecioCompra;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECPRODUCTO", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="precio", nullable=false, precision=10, scale=0)
    public long getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(long precio) {
        this.precio = precio;
    }
    
    @Column(name="activo")
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }




}


