package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {
    private static final long serialVersionUID = 6495500434092138273L;


     private Integer idProducto;
     private Casino casino;
     private Categoria categoria;
     private Ubicacion ubicacion;
     private Tblunidad tblunidad;
     private String descripcion;
     private int cantidadActual;
     private long precioVenta1;
     private Long precioVenta2;
     private String codigoBarras;
     private int cantidadMinima;
     private String imagen;
     private Set<TbldetalleVenta> tbldetalleVentas = new HashSet<TbldetalleVenta>(0);
     private Set<Tbldetallepedido> tbldetallepedidos = new HashSet<Tbldetallepedido>(0);
     private Set<Tbldetallecompra> tbldetallecompras = new HashSet<Tbldetallecompra>(0);
     private Set<PrecioCompra> precioCompras = new HashSet<PrecioCompra>(0);

    public Producto() {
    }

	
    public Producto(Casino casino, Categoria categoria, Ubicacion ubicacion, Tblunidad tblunidad, String descripcion, int cantidadActual, long precioVenta1, String codigoBarras, int cantidadMinima) {
        this.casino = casino;
        this.categoria = categoria;
        this.ubicacion = ubicacion;
        this.tblunidad = tblunidad;
        this.descripcion = descripcion;
        this.cantidadActual = cantidadActual;
        this.precioVenta1 = precioVenta1;
        this.codigoBarras = codigoBarras;
        this.cantidadMinima = cantidadMinima;
    }
    public Producto(Casino casino, Categoria categoria, Ubicacion ubicacion, Tblunidad tblunidad, String descripcion, int cantidadActual, long precioVenta1, Long precioVenta2, String codigoBarras, int cantidadMinima, String imagen, Set<TbldetalleVenta> tbldetalleVentas, Set<Tbldetallepedido> tbldetallepedidos, Set<Tbldetallecompra> tbldetallecompras, Set<PrecioCompra> precioCompras) {
       this.casino = casino;
       this.categoria = categoria;
       this.ubicacion = ubicacion;
       this.tblunidad = tblunidad;
       this.descripcion = descripcion;
       this.cantidadActual = cantidadActual;
       this.precioVenta1 = precioVenta1;
       this.precioVenta2 = precioVenta2;
       this.codigoBarras = codigoBarras;
       this.cantidadMinima = cantidadMinima;
       this.imagen = imagen;
       this.tbldetalleVentas = tbldetalleVentas;
       this.tbldetallepedidos = tbldetallepedidos;
       this.tbldetallecompras = tbldetallecompras;
       this.precioCompras = precioCompras;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Casino getCasino() {
        return this.casino;
    }
    
    public void setCasino(Casino casino) {
        this.casino = casino;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Ubicacion getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Tblunidad getTblunidad() {
        return this.tblunidad;
    }
    
    public void setTblunidad(Tblunidad tblunidad) {
        this.tblunidad = tblunidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getCantidadActual() {
        return this.cantidadActual;
    }
    
    public void setCantidadActual(int cantidadActual) {
        this.cantidadActual = cantidadActual;
    }
    public long getPrecioVenta1() {
        return this.precioVenta1;
    }
    
    public void setPrecioVenta1(long precioVenta1) {
        this.precioVenta1 = precioVenta1;
    }
    public Long getPrecioVenta2() {
        return this.precioVenta2;
    }
    
    public void setPrecioVenta2(Long precioVenta2) {
        this.precioVenta2 = precioVenta2;
    }
    public String getCodigoBarras() {
        return this.codigoBarras;
    }
    
    public void setCodigoBarras(String codigoBarras) {
        this.codigoBarras = codigoBarras;
    }
    public int getCantidadMinima() {
        return this.cantidadMinima;
    }
    
    public void setCantidadMinima(int cantidadMinima) {
        this.cantidadMinima = cantidadMinima;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Set<TbldetalleVenta> getTbldetalleVentas() {
        return this.tbldetalleVentas;
    }
    
    public void setTbldetalleVentas(Set<TbldetalleVenta> tbldetalleVentas) {
        this.tbldetalleVentas = tbldetalleVentas;
    }
    public Set<Tbldetallepedido> getTbldetallepedidos() {
        return this.tbldetallepedidos;
    }
    
    public void setTbldetallepedidos(Set<Tbldetallepedido> tbldetallepedidos) {
        this.tbldetallepedidos = tbldetallepedidos;
    }
    public Set<Tbldetallecompra> getTbldetallecompras() {
        return this.tbldetallecompras;
    }
    
    public void setTbldetallecompras(Set<Tbldetallecompra> tbldetallecompras) {
        this.tbldetallecompras = tbldetallecompras;
    }
    public Set<PrecioCompra> getPrecioCompras() {
        return this.precioCompras;
    }
    
    public void setPrecioCompras(Set<PrecioCompra> precioCompras) {
        this.precioCompras = precioCompras;
    }




}


