package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sexo generated by hbm2java
 */
public class Sexo  implements java.io.Serializable {
    private static final long serialVersionUID = 5048971482280777001L;


     private Integer idSexo;
     private String nombreSexo;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public Sexo() {
    }

	
    public Sexo(String nombreSexo) {
        this.nombreSexo = nombreSexo;
    }
    public Sexo(String nombreSexo, Set<Persona> personas) {
       this.nombreSexo = nombreSexo;
       this.personas = personas;
    }
   
    public Integer getIdSexo() {
        return this.idSexo;
    }
    
    public void setIdSexo(Integer idSexo) {
        this.idSexo = idSexo;
    }
    public String getNombreSexo() {
        return this.nombreSexo;
    }
    
    public void setNombreSexo(String nombreSexo) {
        this.nombreSexo = nombreSexo;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


