package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblcompra generated by hbm2java
 */
public class Tblcompra  implements java.io.Serializable {
    private static final long serialVersionUID = -2710839289183682943L;


     private Integer seccompra;
     private Casino casino;
     private Tblproveedor tblproveedor;
     private TblformaPago tblformaPago;
     private Long total;
     private Integer totalcantidad;
     private Date fecha;
     private String observacion;
     private Long subtotal;
     private Long iva;
     private Set<Tblcompracredito> tblcompracreditos = new HashSet<Tblcompracredito>(0);
     private Set<Tbldetallecompra> tbldetallecompras = new HashSet<Tbldetallecompra>(0);
     private Set<Tblcompraefectivo> tblcompraefectivos = new HashSet<Tblcompraefectivo>(0);
     private Set<Tblegreso> tblegresos = new HashSet<Tblegreso>(0);

    public Tblcompra() {
    }

	
    public Tblcompra(Casino casino, Tblproveedor tblproveedor, TblformaPago tblformaPago, Date fecha) {
        this.casino = casino;
        this.tblproveedor = tblproveedor;
        this.tblformaPago = tblformaPago;
        this.fecha = fecha;
    }
    public Tblcompra(Casino casino, Tblproveedor tblproveedor, TblformaPago tblformaPago, Long total, Integer totalcantidad, Date fecha, String observacion, Long subtotal, Long iva, Set<Tblcompracredito> tblcompracreditos, Set<Tbldetallecompra> tbldetallecompras, Set<Tblcompraefectivo> tblcompraefectivos, Set<Tblegreso> tblegresos) {
       this.casino = casino;
       this.tblproveedor = tblproveedor;
       this.tblformaPago = tblformaPago;
       this.total = total;
       this.totalcantidad = totalcantidad;
       this.fecha = fecha;
       this.observacion = observacion;
       this.subtotal = subtotal;
       this.iva = iva;
       this.tblcompracreditos = tblcompracreditos;
       this.tbldetallecompras = tbldetallecompras;
       this.tblcompraefectivos = tblcompraefectivos;
       this.tblegresos = tblegresos;
    }
   
    public Integer getSeccompra() {
        return this.seccompra;
    }
    
    public void setSeccompra(Integer seccompra) {
        this.seccompra = seccompra;
    }
    public Casino getCasino() {
        return this.casino;
    }
    
    public void setCasino(Casino casino) {
        this.casino = casino;
    }
    public Tblproveedor getTblproveedor() {
        return this.tblproveedor;
    }
    
    public void setTblproveedor(Tblproveedor tblproveedor) {
        this.tblproveedor = tblproveedor;
    }
    public TblformaPago getTblformaPago() {
        return this.tblformaPago;
    }
    
    public void setTblformaPago(TblformaPago tblformaPago) {
        this.tblformaPago = tblformaPago;
    }
    public Long getTotal() {
        return this.total;
    }
    
    public void setTotal(Long total) {
        this.total = total;
    }
    public Integer getTotalcantidad() {
        return this.totalcantidad;
    }
    
    public void setTotalcantidad(Integer totalcantidad) {
        this.totalcantidad = totalcantidad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Long getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Long subtotal) {
        this.subtotal = subtotal;
    }
    public Long getIva() {
        return this.iva;
    }
    
    public void setIva(Long iva) {
        this.iva = iva;
    }
    public Set<Tblcompracredito> getTblcompracreditos() {
        return this.tblcompracreditos;
    }
    
    public void setTblcompracreditos(Set<Tblcompracredito> tblcompracreditos) {
        this.tblcompracreditos = tblcompracreditos;
    }
    public Set<Tbldetallecompra> getTbldetallecompras() {
        return this.tbldetallecompras;
    }
    
    public void setTbldetallecompras(Set<Tbldetallecompra> tbldetallecompras) {
        this.tbldetallecompras = tbldetallecompras;
    }
    public Set<Tblcompraefectivo> getTblcompraefectivos() {
        return this.tblcompraefectivos;
    }
    
    public void setTblcompraefectivos(Set<Tblcompraefectivo> tblcompraefectivos) {
        this.tblcompraefectivos = tblcompraefectivos;
    }
    public Set<Tblegreso> getTblegresos() {
        return this.tblegresos;
    }
    
    public void setTblegresos(Set<Tblegreso> tblegresos) {
        this.tblegresos = tblegresos;
    }




}


