package com.pasantia.entidades;
// Generated 10/09/2013 10:40:59 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblcompra generated by hbm2java
 */
@Entity
@Table(name="TBLCOMPRA"
    ,catalog="CasinoPasantia"
)
public class Tblcompra  implements java.io.Serializable {


     private Integer seccompra;
     private Casino casino;
     private Tblproveedor tblproveedor;
     private TblformaPago tblformaPago;
     private Long total;
     private Integer totalcantidad;
     private Date fecha;
     private String observacion;
     private Long subtotal;
     private Long iva;
     private Set tblcompracreditos = new HashSet(0);
     private Set tbldetallecompras = new HashSet(0);
     private Set tblcompraefectivos = new HashSet(0);
     private Set tblegresos = new HashSet(0);

    public Tblcompra() {
    }

	
    public Tblcompra(Casino casino, Tblproveedor tblproveedor, TblformaPago tblformaPago, Date fecha) {
        this.casino = casino;
        this.tblproveedor = tblproveedor;
        this.tblformaPago = tblformaPago;
        this.fecha = fecha;
    }
    public Tblcompra(Casino casino, Tblproveedor tblproveedor, TblformaPago tblformaPago, Long total, Integer totalcantidad, Date fecha, String observacion, Long subtotal, Long iva, Set tblcompracreditos, Set tbldetallecompras, Set tblcompraefectivos, Set tblegresos) {
       this.casino = casino;
       this.tblproveedor = tblproveedor;
       this.tblformaPago = tblformaPago;
       this.total = total;
       this.totalcantidad = totalcantidad;
       this.fecha = fecha;
       this.observacion = observacion;
       this.subtotal = subtotal;
       this.iva = iva;
       this.tblcompracreditos = tblcompracreditos;
       this.tbldetallecompras = tbldetallecompras;
       this.tblcompraefectivos = tblcompraefectivos;
       this.tblegresos = tblegresos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECCOMPRA", unique=true, nullable=false)
    public Integer getSeccompra() {
        return this.seccompra;
    }
    
    public void setSeccompra(Integer seccompra) {
        this.seccompra = seccompra;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECCASINO", nullable=false)
    public Casino getCasino() {
        return this.casino;
    }
    
    public void setCasino(Casino casino) {
        this.casino = casino;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECPROVEEDOR", nullable=false)
    public Tblproveedor getTblproveedor() {
        return this.tblproveedor;
    }
    
    public void setTblproveedor(Tblproveedor tblproveedor) {
        this.tblproveedor = tblproveedor;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECFORMAPAGO", nullable=false)
    public TblformaPago getTblformaPago() {
        return this.tblformaPago;
    }
    
    public void setTblformaPago(TblformaPago tblformaPago) {
        this.tblformaPago = tblformaPago;
    }
    
    @Column(name="TOTAL", precision=10, scale=0)
    public Long getTotal() {
        return this.total;
    }
    
    public void setTotal(Long total) {
        this.total = total;
    }
    
    @Column(name="TOTALCANTIDAD")
    public Integer getTotalcantidad() {
        return this.totalcantidad;
    }
    
    public void setTotalcantidad(Integer totalcantidad) {
        this.totalcantidad = totalcantidad;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="OBSERVACION", length=45)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    
    @Column(name="SUBTOTAL", precision=10, scale=0)
    public Long getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Long subtotal) {
        this.subtotal = subtotal;
    }
    
    @Column(name="IVA", precision=10, scale=0)
    public Long getIva() {
        return this.iva;
    }
    
    public void setIva(Long iva) {
        this.iva = iva;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblcompra")
    public Set getTblcompracreditos() {
        return this.tblcompracreditos;
    }
    
    public void setTblcompracreditos(Set tblcompracreditos) {
        this.tblcompracreditos = tblcompracreditos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblcompra")
    public Set getTbldetallecompras() {
        return this.tbldetallecompras;
    }
    
    public void setTbldetallecompras(Set tbldetallecompras) {
        this.tbldetallecompras = tbldetallecompras;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblcompra")
    public Set getTblcompraefectivos() {
        return this.tblcompraefectivos;
    }
    
    public void setTblcompraefectivos(Set tblcompraefectivos) {
        this.tblcompraefectivos = tblcompraefectivos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblcompra")
    public Set getTblegresos() {
        return this.tblegresos;
    }
    
    public void setTblegresos(Set tblegresos) {
        this.tblegresos = tblegresos;
    }




}


