package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tblcompraefectivo generated by hbm2java
 */
public class Tblcompraefectivo  implements java.io.Serializable {
    private static final long serialVersionUID = -6649515704514651597L;


     private Integer seccompraefectivo;
     private Tblcompra tblcompra;
     private Date fechaPago;
     private boolean pagado;

    public Tblcompraefectivo() {
    }

    public Tblcompraefectivo(Tblcompra tblcompra, Date fechaPago, boolean pagado) {
       this.tblcompra = tblcompra;
       this.fechaPago = fechaPago;
       this.pagado = pagado;
    }
   
    public Integer getSeccompraefectivo() {
        return this.seccompraefectivo;
    }
    
    public void setSeccompraefectivo(Integer seccompraefectivo) {
        this.seccompraefectivo = seccompraefectivo;
    }
    public Tblcompra getTblcompra() {
        return this.tblcompra;
    }
    
    public void setTblcompra(Tblcompra tblcompra) {
        this.tblcompra = tblcompra;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public boolean isPagado() {
        return this.pagado;
    }
    
    public void setPagado(boolean pagado) {
        this.pagado = pagado;
    }




}


