package com.pasantia.entidades;
// Generated 10/09/2013 10:40:59 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblcaja generated by hbm2java
 */
@Entity
@Table(name="tblcaja"
    ,catalog="CasinoPasantia"
)
public class Tblcaja  implements java.io.Serializable {


     private Integer seccaja;
     private Tblingreso tblingreso;
     private Tblegreso tblegreso;
     private String total;

    public Tblcaja() {
    }

    public Tblcaja(Tblingreso tblingreso, Tblegreso tblegreso, String total) {
       this.tblingreso = tblingreso;
       this.tblegreso = tblegreso;
       this.total = total;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECCAJA", unique=true, nullable=false)
    public Integer getSeccaja() {
        return this.seccaja;
    }
    
    public void setSeccaja(Integer seccaja) {
        this.seccaja = seccaja;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECINGRESO", nullable=false)
    public Tblingreso getTblingreso() {
        return this.tblingreso;
    }
    
    public void setTblingreso(Tblingreso tblingreso) {
        this.tblingreso = tblingreso;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECEGRESO", nullable=false)
    public Tblegreso getTblegreso() {
        return this.tblegreso;
    }
    
    public void setTblegreso(Tblegreso tblegreso) {
        this.tblegreso = tblegreso;
    }
    
    @Column(name="TOTAL", nullable=false, length=45)
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }




}


