package com.pasantia.entidades;
// Generated 23/09/2013 01:53:37 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblcompraefectivo generated by hbm2java
 */
@Entity
@Table(name="tblcompraefectivo"
    ,catalog="CasinoPasantia"
)
public class Tblcompraefectivo  implements java.io.Serializable {


     private Integer seccompraefectivo;
     private Tblcompra tblcompra;
     private Date fechaPago;
     private boolean pagado;

    public Tblcompraefectivo() {
    }

    public Tblcompraefectivo(Tblcompra tblcompra, Date fechaPago, boolean pagado) {
       this.tblcompra = tblcompra;
       this.fechaPago = fechaPago;
       this.pagado = pagado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECCOMPRAEFECTIVO", unique=true, nullable=false)
    public Integer getSeccompraefectivo() {
        return this.seccompraefectivo;
    }
    
    public void setSeccompraefectivo(Integer seccompraefectivo) {
        this.seccompraefectivo = seccompraefectivo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECCOMPRA", nullable=false)
    public Tblcompra getTblcompra() {
        return this.tblcompra;
    }
    
    public void setTblcompra(Tblcompra tblcompra) {
        this.tblcompra = tblcompra;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_PAGO", nullable=false, length=10)
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    
    @Column(name="PAGADO", nullable=false)
    public boolean isPagado() {
        return this.pagado;
    }
    
    public void setPagado(boolean pagado) {
        this.pagado = pagado;
    }




}


