package com.pasantia.entidades;
// Generated 6/10/2013 04:27:25 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblcaja generated by hbm2java
 */
@Entity
@Table(name="tblcaja"
    ,catalog="CasinoPasantia"
)
public class Tblcaja  implements java.io.Serializable {


     private Integer seccaja;
     private Tblingreso tblingreso;
     private Tblegreso tblegreso;
     private long total;

    public Tblcaja() {
    }

    public Tblcaja(Tblingreso tblingreso, Tblegreso tblegreso, long total) {
       this.tblingreso = tblingreso;
       this.tblegreso = tblegreso;
       this.total = total;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECCAJA", unique=true, nullable=false)
    public Integer getSeccaja() {
        return this.seccaja;
    }
    
    public void setSeccaja(Integer seccaja) {
        this.seccaja = seccaja;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECINGRESO", nullable=false)
    public Tblingreso getTblingreso() {
        return this.tblingreso;
    }
    
    public void setTblingreso(Tblingreso tblingreso) {
        this.tblingreso = tblingreso;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECEGRESO", nullable=false)
    public Tblegreso getTblegreso() {
        return this.tblegreso;
    }
    
    public void setTblegreso(Tblegreso tblegreso) {
        this.tblegreso = tblegreso;
    }
    
    @Column(name="TOTAL", nullable=false, precision=10, scale=0)
    public long getTotal() {
        return this.total;
    }
    
    public void setTotal(long total) {
        this.total = total;
    }




}


