package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tblcompracredito generated by hbm2java
 */
public class Tblcompracredito  implements java.io.Serializable {
    private static final long serialVersionUID = 6996743836284029052L;


     private Integer secompracredito;
     private Tblcompra tblcompra;
     private Date fechaPago;
     private boolean pagado;

    public Tblcompracredito() {
    }

    public Tblcompracredito(Tblcompra tblcompra, Date fechaPago, boolean pagado) {
       this.tblcompra = tblcompra;
       this.fechaPago = fechaPago;
       this.pagado = pagado;
    }
   
    public Integer getSecompracredito() {
        return this.secompracredito;
    }
    
    public void setSecompracredito(Integer secompracredito) {
        this.secompracredito = secompracredito;
    }
    public Tblcompra getTblcompra() {
        return this.tblcompra;
    }
    
    public void setTblcompra(Tblcompra tblcompra) {
        this.tblcompra = tblcompra;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public boolean isPagado() {
        return this.pagado;
    }
    
    public void setPagado(boolean pagado) {
        this.pagado = pagado;
    }




}


