package com.pasantia.entidades;
// Generated 23/09/2013 01:53:37 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tbldetallecompra generated by hbm2java
 */
@Entity
@Table(name="TBLDETALLECOMPRA"
    ,catalog="CasinoPasantia"
)
public class Tbldetallecompra  implements java.io.Serializable {


     private Integer idDetalleCompra;
     private Producto producto;
     private Tblcompra tblcompra;
     private int cantidad;
     private long subtotal;
     private Long iva;
     private Set tblinventarios = new HashSet(0);

    public Tbldetallecompra() {
    }

	
    public Tbldetallecompra(Producto producto, Tblcompra tblcompra, int cantidad, long subtotal) {
        this.producto = producto;
        this.tblcompra = tblcompra;
        this.cantidad = cantidad;
        this.subtotal = subtotal;
    }
    public Tbldetallecompra(Producto producto, Tblcompra tblcompra, int cantidad, long subtotal, Long iva, Set tblinventarios) {
       this.producto = producto;
       this.tblcompra = tblcompra;
       this.cantidad = cantidad;
       this.subtotal = subtotal;
       this.iva = iva;
       this.tblinventarios = tblinventarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idDetalle_Compra", unique=true, nullable=false)
    public Integer getIdDetalleCompra() {
        return this.idDetalleCompra;
    }
    
    public void setIdDetalleCompra(Integer idDetalleCompra) {
        this.idDetalleCompra = idDetalleCompra;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECPRODUCTO", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECCOMPRA", nullable=false)
    public Tblcompra getTblcompra() {
        return this.tblcompra;
    }
    
    public void setTblcompra(Tblcompra tblcompra) {
        this.tblcompra = tblcompra;
    }
    
    @Column(name="CANTIDAD", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    
    @Column(name="SUBTOTAL", nullable=false, precision=10, scale=0)
    public long getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(long subtotal) {
        this.subtotal = subtotal;
    }
    
    @Column(name="IVA", precision=10, scale=0)
    public Long getIva() {
        return this.iva;
    }
    
    public void setIva(Long iva) {
        this.iva = iva;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbldetallecompra")
    public Set getTblinventarios() {
        return this.tblinventarios;
    }
    
    public void setTblinventarios(Set tblinventarios) {
        this.tblinventarios = tblinventarios;
    }




}


