package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TbldetalleVenta generated by hbm2java
 */
public class TbldetalleVenta  implements java.io.Serializable {
    private static final long serialVersionUID = 141236672322474965L;


     private Integer idDetalleVenta;
     private Producto producto;
     private Tblventa tblventa;
     private int cantidad;
     private Long subtotal;
     private Set<Tblinventario> tblinventarios = new HashSet<Tblinventario>(0);

    public TbldetalleVenta() {
    }

	
    public TbldetalleVenta(Producto producto, Tblventa tblventa, int cantidad) {
        this.producto = producto;
        this.tblventa = tblventa;
        this.cantidad = cantidad;
    }
    public TbldetalleVenta(Producto producto, Tblventa tblventa, int cantidad, Long subtotal, Set<Tblinventario> tblinventarios) {
       this.producto = producto;
       this.tblventa = tblventa;
       this.cantidad = cantidad;
       this.subtotal = subtotal;
       this.tblinventarios = tblinventarios;
    }
   
    public Integer getIdDetalleVenta() {
        return this.idDetalleVenta;
    }
    
    public void setIdDetalleVenta(Integer idDetalleVenta) {
        this.idDetalleVenta = idDetalleVenta;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Tblventa getTblventa() {
        return this.tblventa;
    }
    
    public void setTblventa(Tblventa tblventa) {
        this.tblventa = tblventa;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Long getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Long subtotal) {
        this.subtotal = subtotal;
    }
    public Set<Tblinventario> getTblinventarios() {
        return this.tblinventarios;
    }
    
    public void setTblinventarios(Set<Tblinventario> tblinventarios) {
        this.tblinventarios = tblinventarios;
    }




}


