package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tbldetallecompra generated by hbm2java
 */
public class Tbldetallecompra  implements java.io.Serializable {
    private static final long serialVersionUID = -3679409558637080083L;


     private Integer idDetalleCompra;
     private Producto producto;
     private Tblcompra tblcompra;
     private int cantidad;
     private long subtotal;
     private Long iva;
     private Set<Tblinventario> tblinventarios = new HashSet<Tblinventario>(0);

    public Tbldetallecompra() {
    }

	
    public Tbldetallecompra(Producto producto, Tblcompra tblcompra, int cantidad, long subtotal) {
        this.producto = producto;
        this.tblcompra = tblcompra;
        this.cantidad = cantidad;
        this.subtotal = subtotal;
    }
    public Tbldetallecompra(Producto producto, Tblcompra tblcompra, int cantidad, long subtotal, Long iva, Set<Tblinventario> tblinventarios) {
       this.producto = producto;
       this.tblcompra = tblcompra;
       this.cantidad = cantidad;
       this.subtotal = subtotal;
       this.iva = iva;
       this.tblinventarios = tblinventarios;
    }
   
    public Integer getIdDetalleCompra() {
        return this.idDetalleCompra;
    }
    
    public void setIdDetalleCompra(Integer idDetalleCompra) {
        this.idDetalleCompra = idDetalleCompra;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Tblcompra getTblcompra() {
        return this.tblcompra;
    }
    
    public void setTblcompra(Tblcompra tblcompra) {
        this.tblcompra = tblcompra;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public long getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(long subtotal) {
        this.subtotal = subtotal;
    }
    public Long getIva() {
        return this.iva;
    }
    
    public void setIva(Long iva) {
        this.iva = iva;
    }
    public Set<Tblinventario> getTblinventarios() {
        return this.tblinventarios;
    }
    
    public void setTblinventarios(Set<Tblinventario> tblinventarios) {
        this.tblinventarios = tblinventarios;
    }




}


