package com.pasantia.entidades;
// Generated 10/09/2013 10:40:59 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbldetalleVenta generated by hbm2java
 */
@Entity
@Table(name="TBLDETALLE_VENTA"
    ,catalog="CasinoPasantia"
)
public class TbldetalleVenta  implements java.io.Serializable {


     private Integer idDetalleVenta;
     private Producto producto;
     private Tblventa tblventa;
     private int cantidad;
     private Long subtotal;
     private Set tblinventarios = new HashSet(0);

    public TbldetalleVenta() {
    }

	
    public TbldetalleVenta(Producto producto, Tblventa tblventa, int cantidad) {
        this.producto = producto;
        this.tblventa = tblventa;
        this.cantidad = cantidad;
    }
    public TbldetalleVenta(Producto producto, Tblventa tblventa, int cantidad, Long subtotal, Set tblinventarios) {
       this.producto = producto;
       this.tblventa = tblventa;
       this.cantidad = cantidad;
       this.subtotal = subtotal;
       this.tblinventarios = tblinventarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idDetalle_Venta", unique=true, nullable=false)
    public Integer getIdDetalleVenta() {
        return this.idDetalleVenta;
    }
    
    public void setIdDetalleVenta(Integer idDetalleVenta) {
        this.idDetalleVenta = idDetalleVenta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECPRODUCTO", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECVENTA", nullable=false)
    public Tblventa getTblventa() {
        return this.tblventa;
    }
    
    public void setTblventa(Tblventa tblventa) {
        this.tblventa = tblventa;
    }
    
    @Column(name="CANTIDAD", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    
    @Column(name="SUBTOTAL", precision=10, scale=0)
    public Long getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Long subtotal) {
        this.subtotal = subtotal;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbldetalleVenta")
    public Set getTblinventarios() {
        return this.tblinventarios;
    }
    
    public void setTblinventarios(Set tblinventarios) {
        this.tblinventarios = tblinventarios;
    }




}


