package com.pasantia.entidades;
// Generated 23/09/2013 01:53:37 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tbldetallepedido generated by hbm2java
 */
@Entity
@Table(name="TBLDETALLEPEDIDO"
    ,catalog="CasinoPasantia"
)
public class Tbldetallepedido  implements java.io.Serializable {


     private Integer secdetallepedido;
     private Producto producto;
     private Tblpedido tblpedido;
     private Integer cantidad;
     private Long subtotal;

    public Tbldetallepedido() {
    }

	
    public Tbldetallepedido(Producto producto, Tblpedido tblpedido) {
        this.producto = producto;
        this.tblpedido = tblpedido;
    }
    public Tbldetallepedido(Producto producto, Tblpedido tblpedido, Integer cantidad, Long subtotal) {
       this.producto = producto;
       this.tblpedido = tblpedido;
       this.cantidad = cantidad;
       this.subtotal = subtotal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECDETALLEPEDIDO", unique=true, nullable=false)
    public Integer getSecdetallepedido() {
        return this.secdetallepedido;
    }
    
    public void setSecdetallepedido(Integer secdetallepedido) {
        this.secdetallepedido = secdetallepedido;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECPRODUCTO", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECPEDIDO", nullable=false)
    public Tblpedido getTblpedido() {
        return this.tblpedido;
    }
    
    public void setTblpedido(Tblpedido tblpedido) {
        this.tblpedido = tblpedido;
    }
    
    @Column(name="CANTIDAD")
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    
    @Column(name="SUBTOTAL", precision=10, scale=0)
    public Long getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Long subtotal) {
        this.subtotal = subtotal;
    }




}


