package com.pasantia.entidades;
// Generated 23/09/2013 01:53:37 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblentregapedido generated by hbm2java
 */
@Entity
@Table(name="tblentregapedido"
    ,catalog="CasinoPasantia"
)
public class Tblentregapedido  implements java.io.Serializable {


     private Integer secentregapedido;
     private Tblpedido tblpedido;
     private Boolean lunes;
     private Boolean martes;
     private Boolean miercoles;
     private Boolean jueves;
     private Boolean viernes;
     private Boolean sabado;
     private Boolean domingo;
     private Set tblproveedors = new HashSet(0);

    public Tblentregapedido() {
    }

	
    public Tblentregapedido(Tblpedido tblpedido) {
        this.tblpedido = tblpedido;
    }
    public Tblentregapedido(Tblpedido tblpedido, Boolean lunes, Boolean martes, Boolean miercoles, Boolean jueves, Boolean viernes, Boolean sabado, Boolean domingo, Set tblproveedors) {
       this.tblpedido = tblpedido;
       this.lunes = lunes;
       this.martes = martes;
       this.miercoles = miercoles;
       this.jueves = jueves;
       this.viernes = viernes;
       this.sabado = sabado;
       this.domingo = domingo;
       this.tblproveedors = tblproveedors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECENTREGAPEDIDO", unique=true, nullable=false)
    public Integer getSecentregapedido() {
        return this.secentregapedido;
    }
    
    public void setSecentregapedido(Integer secentregapedido) {
        this.secentregapedido = secentregapedido;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECPEDIDO", nullable=false)
    public Tblpedido getTblpedido() {
        return this.tblpedido;
    }
    
    public void setTblpedido(Tblpedido tblpedido) {
        this.tblpedido = tblpedido;
    }
    
    @Column(name="LUNES")
    public Boolean getLunes() {
        return this.lunes;
    }
    
    public void setLunes(Boolean lunes) {
        this.lunes = lunes;
    }
    
    @Column(name="MARTES")
    public Boolean getMartes() {
        return this.martes;
    }
    
    public void setMartes(Boolean martes) {
        this.martes = martes;
    }
    
    @Column(name="MIERCOLES")
    public Boolean getMiercoles() {
        return this.miercoles;
    }
    
    public void setMiercoles(Boolean miercoles) {
        this.miercoles = miercoles;
    }
    
    @Column(name="JUEVES")
    public Boolean getJueves() {
        return this.jueves;
    }
    
    public void setJueves(Boolean jueves) {
        this.jueves = jueves;
    }
    
    @Column(name="VIERNES")
    public Boolean getViernes() {
        return this.viernes;
    }
    
    public void setViernes(Boolean viernes) {
        this.viernes = viernes;
    }
    
    @Column(name="SABADO")
    public Boolean getSabado() {
        return this.sabado;
    }
    
    public void setSabado(Boolean sabado) {
        this.sabado = sabado;
    }
    
    @Column(name="DOMINGO")
    public Boolean getDomingo() {
        return this.domingo;
    }
    
    public void setDomingo(Boolean domingo) {
        this.domingo = domingo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblentregapedido")
    public Set getTblproveedors() {
        return this.tblproveedors;
    }
    
    public void setTblproveedors(Set tblproveedors) {
        this.tblproveedors = tblproveedors;
    }




}


