package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblentregapedido generated by hbm2java
 */
public class Tblentregapedido  implements java.io.Serializable {
    private static final long serialVersionUID = 2961573407507736949L;


     private Integer secentregapedido;
     private Tblpedido tblpedido;
     private Boolean lunes;
     private Boolean martes;
     private Boolean miercoles;
     private Boolean jueves;
     private Boolean viernes;
     private Boolean sabado;
     private Boolean domingo;
     private Set<Tblproveedor> tblproveedors = new HashSet<Tblproveedor>(0);

    public Tblentregapedido() {
    }

	
    public Tblentregapedido(Tblpedido tblpedido) {
        this.tblpedido = tblpedido;
    }
    public Tblentregapedido(Tblpedido tblpedido, Boolean lunes, Boolean martes, Boolean miercoles, Boolean jueves, Boolean viernes, Boolean sabado, Boolean domingo, Set<Tblproveedor> tblproveedors) {
       this.tblpedido = tblpedido;
       this.lunes = lunes;
       this.martes = martes;
       this.miercoles = miercoles;
       this.jueves = jueves;
       this.viernes = viernes;
       this.sabado = sabado;
       this.domingo = domingo;
       this.tblproveedors = tblproveedors;
    }
   
    public Integer getSecentregapedido() {
        return this.secentregapedido;
    }
    
    public void setSecentregapedido(Integer secentregapedido) {
        this.secentregapedido = secentregapedido;
    }
    public Tblpedido getTblpedido() {
        return this.tblpedido;
    }
    
    public void setTblpedido(Tblpedido tblpedido) {
        this.tblpedido = tblpedido;
    }
    public Boolean getLunes() {
        return this.lunes;
    }
    
    public void setLunes(Boolean lunes) {
        this.lunes = lunes;
    }
    public Boolean getMartes() {
        return this.martes;
    }
    
    public void setMartes(Boolean martes) {
        this.martes = martes;
    }
    public Boolean getMiercoles() {
        return this.miercoles;
    }
    
    public void setMiercoles(Boolean miercoles) {
        this.miercoles = miercoles;
    }
    public Boolean getJueves() {
        return this.jueves;
    }
    
    public void setJueves(Boolean jueves) {
        this.jueves = jueves;
    }
    public Boolean getViernes() {
        return this.viernes;
    }
    
    public void setViernes(Boolean viernes) {
        this.viernes = viernes;
    }
    public Boolean getSabado() {
        return this.sabado;
    }
    
    public void setSabado(Boolean sabado) {
        this.sabado = sabado;
    }
    public Boolean getDomingo() {
        return this.domingo;
    }
    
    public void setDomingo(Boolean domingo) {
        this.domingo = domingo;
    }
    public Set<Tblproveedor> getTblproveedors() {
        return this.tblproveedors;
    }
    
    public void setTblproveedors(Set<Tblproveedor> tblproveedors) {
        this.tblproveedors = tblproveedors;
    }




}


