package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblegreso generated by hbm2java
 */
public class Tblegreso  implements java.io.Serializable {
    private static final long serialVersionUID = 4397407947505170062L;


     private Integer secegreso;
     private Tbltipoegreso tbltipoegreso;
     private Tblcompra tblcompra;
     private Date fecha;
     private Set<Tblcaja> tblcajas = new HashSet<Tblcaja>(0);

    public Tblegreso() {
    }

	
    public Tblegreso(Tbltipoegreso tbltipoegreso, Tblcompra tblcompra, Date fecha) {
        this.tbltipoegreso = tbltipoegreso;
        this.tblcompra = tblcompra;
        this.fecha = fecha;
    }
    public Tblegreso(Tbltipoegreso tbltipoegreso, Tblcompra tblcompra, Date fecha, Set<Tblcaja> tblcajas) {
       this.tbltipoegreso = tbltipoegreso;
       this.tblcompra = tblcompra;
       this.fecha = fecha;
       this.tblcajas = tblcajas;
    }
   
    public Integer getSecegreso() {
        return this.secegreso;
    }
    
    public void setSecegreso(Integer secegreso) {
        this.secegreso = secegreso;
    }
    public Tbltipoegreso getTbltipoegreso() {
        return this.tbltipoegreso;
    }
    
    public void setTbltipoegreso(Tbltipoegreso tbltipoegreso) {
        this.tbltipoegreso = tbltipoegreso;
    }
    public Tblcompra getTblcompra() {
        return this.tblcompra;
    }
    
    public void setTblcompra(Tblcompra tblcompra) {
        this.tblcompra = tblcompra;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set<Tblcaja> getTblcajas() {
        return this.tblcajas;
    }
    
    public void setTblcajas(Set<Tblcaja> tblcajas) {
        this.tblcajas = tblcajas;
    }




}


