package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TblformaPago generated by hbm2java
 */
public class TblformaPago  implements java.io.Serializable {
    private static final long serialVersionUID = 3048355351246994546L;


     private Integer secformaPago;
     private String descripcion;
     private Set<Tblcompra> tblcompras = new HashSet<Tblcompra>(0);
     private Set<Tblventa> tblventas = new HashSet<Tblventa>(0);

    public TblformaPago() {
    }

	
    public TblformaPago(String descripcion) {
        this.descripcion = descripcion;
    }
    public TblformaPago(String descripcion, Set<Tblcompra> tblcompras, Set<Tblventa> tblventas) {
       this.descripcion = descripcion;
       this.tblcompras = tblcompras;
       this.tblventas = tblventas;
    }
   
    public Integer getSecformaPago() {
        return this.secformaPago;
    }
    
    public void setSecformaPago(Integer secformaPago) {
        this.secformaPago = secformaPago;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Tblcompra> getTblcompras() {
        return this.tblcompras;
    }
    
    public void setTblcompras(Set<Tblcompra> tblcompras) {
        this.tblcompras = tblcompras;
    }
    public Set<Tblventa> getTblventas() {
        return this.tblventas;
    }
    
    public void setTblventas(Set<Tblventa> tblventas) {
        this.tblventas = tblventas;
    }




}


