package com.pasantia.entidades;
// Generated 6/10/2013 04:27:25 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblformaPago generated by hbm2java
 */
@Entity
@Table(name="TBLFORMA_PAGO"
    ,catalog="CasinoPasantia"
)
public class TblformaPago  implements java.io.Serializable {


     private Integer secformaPago;
     private String descripcion;
     private Set tblcompras = new HashSet(0);
     private Set tblventas = new HashSet(0);

    public TblformaPago() {
    }

	
    public TblformaPago(String descripcion) {
        this.descripcion = descripcion;
    }
    public TblformaPago(String descripcion, Set tblcompras, Set tblventas) {
       this.descripcion = descripcion;
       this.tblcompras = tblcompras;
       this.tblventas = tblventas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECFORMA_PAGO", unique=true, nullable=false)
    public Integer getSecformaPago() {
        return this.secformaPago;
    }
    
    public void setSecformaPago(Integer secformaPago) {
        this.secformaPago = secformaPago;
    }
    
    @Column(name="DESCRIPCION", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblformaPago")
    public Set getTblcompras() {
        return this.tblcompras;
    }
    
    public void setTblcompras(Set tblcompras) {
        this.tblcompras = tblcompras;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblformaPago")
    public Set getTblventas() {
        return this.tblventas;
    }
    
    public void setTblventas(Set tblventas) {
        this.tblventas = tblventas;
    }




}


