package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA



/**
 * Tblinventario generated by hbm2java
 */
public class Tblinventario  implements java.io.Serializable {
    private static final long serialVersionUID = -5242665864369301480L;


     private Integer secinventario;
     private TbldetalleVenta tbldetalleVenta;
     private Tbldetallecompra tbldetallecompra;
     private long totalCantidad;
     private long totalCompra;
     private long totalCompras;

    public Tblinventario() {
    }

    public Tblinventario(TbldetalleVenta tbldetalleVenta, Tbldetallecompra tbldetallecompra, long totalCantidad, long totalCompra, long totalCompras) {
       this.tbldetalleVenta = tbldetalleVenta;
       this.tbldetallecompra = tbldetallecompra;
       this.totalCantidad = totalCantidad;
       this.totalCompra = totalCompra;
       this.totalCompras = totalCompras;
    }
   
    public Integer getSecinventario() {
        return this.secinventario;
    }
    
    public void setSecinventario(Integer secinventario) {
        this.secinventario = secinventario;
    }
    public TbldetalleVenta getTbldetalleVenta() {
        return this.tbldetalleVenta;
    }
    
    public void setTbldetalleVenta(TbldetalleVenta tbldetalleVenta) {
        this.tbldetalleVenta = tbldetalleVenta;
    }
    public Tbldetallecompra getTbldetallecompra() {
        return this.tbldetallecompra;
    }
    
    public void setTbldetallecompra(Tbldetallecompra tbldetallecompra) {
        this.tbldetallecompra = tbldetallecompra;
    }
    public long getTotalCantidad() {
        return this.totalCantidad;
    }
    
    public void setTotalCantidad(long totalCantidad) {
        this.totalCantidad = totalCantidad;
    }
    public long getTotalCompra() {
        return this.totalCompra;
    }
    
    public void setTotalCompra(long totalCompra) {
        this.totalCompra = totalCompra;
    }
    public long getTotalCompras() {
        return this.totalCompras;
    }
    
    public void setTotalCompras(long totalCompras) {
        this.totalCompras = totalCompras;
    }




}


