package com.pasantia.entidades;
// Generated 23/09/2013 01:53:37 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblinventario generated by hbm2java
 */
@Entity
@Table(name="tblinventario"
    ,catalog="CasinoPasantia"
)
public class Tblinventario  implements java.io.Serializable {


     private Integer secinventario;
     private TbldetalleVenta tbldetalleVenta;
     private Tbldetallecompra tbldetallecompra;
     private String totalCantidad;
     private String totalCompra;
     private String totalCompras;

    public Tblinventario() {
    }

    public Tblinventario(TbldetalleVenta tbldetalleVenta, Tbldetallecompra tbldetallecompra, String totalCantidad, String totalCompra, String totalCompras) {
       this.tbldetalleVenta = tbldetalleVenta;
       this.tbldetallecompra = tbldetallecompra;
       this.totalCantidad = totalCantidad;
       this.totalCompra = totalCompra;
       this.totalCompras = totalCompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECINVENTARIO", unique=true, nullable=false)
    public Integer getSecinventario() {
        return this.secinventario;
    }
    
    public void setSecinventario(Integer secinventario) {
        this.secinventario = secinventario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECDETALLEVENTA", nullable=false)
    public TbldetalleVenta getTbldetalleVenta() {
        return this.tbldetalleVenta;
    }
    
    public void setTbldetalleVenta(TbldetalleVenta tbldetalleVenta) {
        this.tbldetalleVenta = tbldetalleVenta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECDETALLECOMPRA", nullable=false)
    public Tbldetallecompra getTbldetallecompra() {
        return this.tbldetallecompra;
    }
    
    public void setTbldetallecompra(Tbldetallecompra tbldetallecompra) {
        this.tbldetallecompra = tbldetallecompra;
    }
    
    @Column(name="TOTAL_CANTIDAD", nullable=false, length=45)
    public String getTotalCantidad() {
        return this.totalCantidad;
    }
    
    public void setTotalCantidad(String totalCantidad) {
        this.totalCantidad = totalCantidad;
    }
    
    @Column(name="TOTAL_COMPRA", nullable=false, length=45)
    public String getTotalCompra() {
        return this.totalCompra;
    }
    
    public void setTotalCompra(String totalCompra) {
        this.totalCompra = totalCompra;
    }
    
    @Column(name="TOTAL_COMPRAS", nullable=false, length=45)
    public String getTotalCompras() {
        return this.totalCompras;
    }
    
    public void setTotalCompras(String totalCompras) {
        this.totalCompras = totalCompras;
    }




}


