package com.pasantia.entidades;
// Generated 23/09/2013 01:53:37 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblingreso generated by hbm2java
 */
@Entity
@Table(name="tblingreso"
    ,catalog="CasinoPasantia"
)
public class Tblingreso  implements java.io.Serializable {


     private Integer secingreso;
     private Tbltipoingreso tbltipoingreso;
     private Tblventa tblventa;
     private Date fecha;
     private Set tblcajas = new HashSet(0);

    public Tblingreso() {
    }

	
    public Tblingreso(Tbltipoingreso tbltipoingreso, Tblventa tblventa, Date fecha) {
        this.tbltipoingreso = tbltipoingreso;
        this.tblventa = tblventa;
        this.fecha = fecha;
    }
    public Tblingreso(Tbltipoingreso tbltipoingreso, Tblventa tblventa, Date fecha, Set tblcajas) {
       this.tbltipoingreso = tbltipoingreso;
       this.tblventa = tblventa;
       this.fecha = fecha;
       this.tblcajas = tblcajas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECINGRESO", unique=true, nullable=false)
    public Integer getSecingreso() {
        return this.secingreso;
    }
    
    public void setSecingreso(Integer secingreso) {
        this.secingreso = secingreso;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECTIPOINGRESO", nullable=false)
    public Tbltipoingreso getTbltipoingreso() {
        return this.tbltipoingreso;
    }
    
    public void setTbltipoingreso(Tbltipoingreso tbltipoingreso) {
        this.tbltipoingreso = tbltipoingreso;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECVENTA", nullable=false)
    public Tblventa getTblventa() {
        return this.tblventa;
    }
    
    public void setTblventa(Tblventa tblventa) {
        this.tblventa = tblventa;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblingreso")
    public Set getTblcajas() {
        return this.tblcajas;
    }
    
    public void setTblcajas(Set tblcajas) {
        this.tblcajas = tblcajas;
    }




}


