package com.pasantia.entidades;
// Generated 6/10/2013 04:27:25 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblinventario generated by hbm2java
 */
@Entity
@Table(name="tblinventario"
    ,catalog="CasinoPasantia"
)
public class Tblinventario  implements java.io.Serializable {


     private Integer secinventario;
     private TbldetalleVenta tbldetalleVenta;
     private Tbldetallecompra tbldetallecompra;
     private long totalCantidad;
     private long totalCompra;
     private long totalCompras;

    public Tblinventario() {
    }

    public Tblinventario(TbldetalleVenta tbldetalleVenta, Tbldetallecompra tbldetallecompra, long totalCantidad, long totalCompra, long totalCompras) {
       this.tbldetalleVenta = tbldetalleVenta;
       this.tbldetallecompra = tbldetallecompra;
       this.totalCantidad = totalCantidad;
       this.totalCompra = totalCompra;
       this.totalCompras = totalCompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECINVENTARIO", unique=true, nullable=false)
    public Integer getSecinventario() {
        return this.secinventario;
    }
    
    public void setSecinventario(Integer secinventario) {
        this.secinventario = secinventario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECDETALLEVENTA", nullable=false)
    public TbldetalleVenta getTbldetalleVenta() {
        return this.tbldetalleVenta;
    }
    
    public void setTbldetalleVenta(TbldetalleVenta tbldetalleVenta) {
        this.tbldetalleVenta = tbldetalleVenta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECDETALLECOMPRA", nullable=false)
    public Tbldetallecompra getTbldetallecompra() {
        return this.tbldetallecompra;
    }
    
    public void setTbldetallecompra(Tbldetallecompra tbldetallecompra) {
        this.tbldetallecompra = tbldetallecompra;
    }
    
    @Column(name="TOTAL_CANTIDAD", nullable=false, precision=10, scale=0)
    public long getTotalCantidad() {
        return this.totalCantidad;
    }
    
    public void setTotalCantidad(long totalCantidad) {
        this.totalCantidad = totalCantidad;
    }
    
    @Column(name="TOTAL_COMPRA", nullable=false, precision=10, scale=0)
    public long getTotalCompra() {
        return this.totalCompra;
    }
    
    public void setTotalCompra(long totalCompra) {
        this.totalCompra = totalCompra;
    }
    
    @Column(name="TOTAL_COMPRAS", nullable=false, precision=10, scale=0)
    public long getTotalCompras() {
        return this.totalCompras;
    }
    
    public void setTotalCompras(long totalCompras) {
        this.totalCompras = totalCompras;
    }




}


