package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblingreso generated by hbm2java
 */
public class Tblingreso  implements java.io.Serializable {
    private static final long serialVersionUID = -559256956854263892L;


     private Integer secingreso;
     private Tbltipoingreso tbltipoingreso;
     private Tblventa tblventa;
     private Date fecha;
     private Set<Tblcaja> tblcajas = new HashSet<Tblcaja>(0);

    public Tblingreso() {
    }

	
    public Tblingreso(Tbltipoingreso tbltipoingreso, Tblventa tblventa, Date fecha) {
        this.tbltipoingreso = tbltipoingreso;
        this.tblventa = tblventa;
        this.fecha = fecha;
    }
    public Tblingreso(Tbltipoingreso tbltipoingreso, Tblventa tblventa, Date fecha, Set<Tblcaja> tblcajas) {
       this.tbltipoingreso = tbltipoingreso;
       this.tblventa = tblventa;
       this.fecha = fecha;
       this.tblcajas = tblcajas;
    }
   
    public Integer getSecingreso() {
        return this.secingreso;
    }
    
    public void setSecingreso(Integer secingreso) {
        this.secingreso = secingreso;
    }
    public Tbltipoingreso getTbltipoingreso() {
        return this.tbltipoingreso;
    }
    
    public void setTbltipoingreso(Tbltipoingreso tbltipoingreso) {
        this.tbltipoingreso = tbltipoingreso;
    }
    public Tblventa getTblventa() {
        return this.tblventa;
    }
    
    public void setTblventa(Tblventa tblventa) {
        this.tblventa = tblventa;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set<Tblcaja> getTblcajas() {
        return this.tblcajas;
    }
    
    public void setTblcajas(Set<Tblcaja> tblcajas) {
        this.tblcajas = tblcajas;
    }




}


