package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblpedido generated by hbm2java
 */
public class Tblpedido  implements java.io.Serializable {
    private static final long serialVersionUID = -3724520842885112906L;


     private Integer secpedido;
     private Persona persona;
     private Tblproveedor tblproveedor;
     private long totalpedido;
     private Integer totalCantidad;
     private Date fecha;
     private String observacion;
     private Set<Tblentregapedido> tblentregapedidos = new HashSet<Tblentregapedido>(0);
     private Set<Tbldetallepedido> tbldetallepedidos = new HashSet<Tbldetallepedido>(0);

    public Tblpedido() {
    }

	
    public Tblpedido(Persona persona, Tblproveedor tblproveedor, long totalpedido, Date fecha) {
        this.persona = persona;
        this.tblproveedor = tblproveedor;
        this.totalpedido = totalpedido;
        this.fecha = fecha;
    }
    public Tblpedido(Persona persona, Tblproveedor tblproveedor, long totalpedido, Integer totalCantidad, Date fecha, String observacion, Set<Tblentregapedido> tblentregapedidos, Set<Tbldetallepedido> tbldetallepedidos) {
       this.persona = persona;
       this.tblproveedor = tblproveedor;
       this.totalpedido = totalpedido;
       this.totalCantidad = totalCantidad;
       this.fecha = fecha;
       this.observacion = observacion;
       this.tblentregapedidos = tblentregapedidos;
       this.tbldetallepedidos = tbldetallepedidos;
    }
   
    public Integer getSecpedido() {
        return this.secpedido;
    }
    
    public void setSecpedido(Integer secpedido) {
        this.secpedido = secpedido;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Tblproveedor getTblproveedor() {
        return this.tblproveedor;
    }
    
    public void setTblproveedor(Tblproveedor tblproveedor) {
        this.tblproveedor = tblproveedor;
    }
    public long getTotalpedido() {
        return this.totalpedido;
    }
    
    public void setTotalpedido(long totalpedido) {
        this.totalpedido = totalpedido;
    }
    public Integer getTotalCantidad() {
        return this.totalCantidad;
    }
    
    public void setTotalCantidad(Integer totalCantidad) {
        this.totalCantidad = totalCantidad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Set<Tblentregapedido> getTblentregapedidos() {
        return this.tblentregapedidos;
    }
    
    public void setTblentregapedidos(Set<Tblentregapedido> tblentregapedidos) {
        this.tblentregapedidos = tblentregapedidos;
    }
    public Set<Tbldetallepedido> getTbldetallepedidos() {
        return this.tbldetallepedidos;
    }
    
    public void setTbldetallepedidos(Set<Tbldetallepedido> tbldetallepedidos) {
        this.tbldetallepedidos = tbldetallepedidos;
    }




}


