package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblproveedor generated by hbm2java
 */
public class Tblproveedor  implements java.io.Serializable {
    private static final long serialVersionUID = -7501972338137299573L;


     private Integer secproveedor;
     private Tblentregapedido tblentregapedido;
     private Ciudad ciudad;
     private String nombre;
     private String telefono;
     private String direccion;
     private String nit;
     private String email;
     private Set<Tblcompra> tblcompras = new HashSet<Tblcompra>(0);
     private Set<Tblpedido> tblpedidos = new HashSet<Tblpedido>(0);
     private Set<Tblvisitapedidos> tblvisitapedidoses = new HashSet<Tblvisitapedidos>(0);

    public Tblproveedor() {
    }

	
    public Tblproveedor(Tblentregapedido tblentregapedido, Ciudad ciudad, String nombre, String telefono, String direccion, String nit) {
        this.tblentregapedido = tblentregapedido;
        this.ciudad = ciudad;
        this.nombre = nombre;
        this.telefono = telefono;
        this.direccion = direccion;
        this.nit = nit;
    }
    public Tblproveedor(Tblentregapedido tblentregapedido, Ciudad ciudad, String nombre, String telefono, String direccion, String nit, String email, Set<Tblcompra> tblcompras, Set<Tblpedido> tblpedidos, Set<Tblvisitapedidos> tblvisitapedidoses) {
       this.tblentregapedido = tblentregapedido;
       this.ciudad = ciudad;
       this.nombre = nombre;
       this.telefono = telefono;
       this.direccion = direccion;
       this.nit = nit;
       this.email = email;
       this.tblcompras = tblcompras;
       this.tblpedidos = tblpedidos;
       this.tblvisitapedidoses = tblvisitapedidoses;
    }
   
    public Integer getSecproveedor() {
        return this.secproveedor;
    }
    
    public void setSecproveedor(Integer secproveedor) {
        this.secproveedor = secproveedor;
    }
    public Tblentregapedido getTblentregapedido() {
        return this.tblentregapedido;
    }
    
    public void setTblentregapedido(Tblentregapedido tblentregapedido) {
        this.tblentregapedido = tblentregapedido;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Tblcompra> getTblcompras() {
        return this.tblcompras;
    }
    
    public void setTblcompras(Set<Tblcompra> tblcompras) {
        this.tblcompras = tblcompras;
    }
    public Set<Tblpedido> getTblpedidos() {
        return this.tblpedidos;
    }
    
    public void setTblpedidos(Set<Tblpedido> tblpedidos) {
        this.tblpedidos = tblpedidos;
    }
    public Set<Tblvisitapedidos> getTblvisitapedidoses() {
        return this.tblvisitapedidoses;
    }
    
    public void setTblvisitapedidoses(Set<Tblvisitapedidos> tblvisitapedidoses) {
        this.tblvisitapedidoses = tblvisitapedidoses;
    }




}


