package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tbltipoingreso generated by hbm2java
 */
public class Tbltipoingreso  implements java.io.Serializable {
    private static final long serialVersionUID = -8300620492993573821L;


     private Integer sectipoingreso;
     private String conceptoIngreso;
     private Set<Tblingreso> tblingresos = new HashSet<Tblingreso>(0);

    public Tbltipoingreso() {
    }

	
    public Tbltipoingreso(String conceptoIngreso) {
        this.conceptoIngreso = conceptoIngreso;
    }
    public Tbltipoingreso(String conceptoIngreso, Set<Tblingreso> tblingresos) {
       this.conceptoIngreso = conceptoIngreso;
       this.tblingresos = tblingresos;
    }
   
    public Integer getSectipoingreso() {
        return this.sectipoingreso;
    }
    
    public void setSectipoingreso(Integer sectipoingreso) {
        this.sectipoingreso = sectipoingreso;
    }
    public String getConceptoIngreso() {
        return this.conceptoIngreso;
    }
    
    public void setConceptoIngreso(String conceptoIngreso) {
        this.conceptoIngreso = conceptoIngreso;
    }
    public Set<Tblingreso> getTblingresos() {
        return this.tblingresos;
    }
    
    public void setTblingresos(Set<Tblingreso> tblingresos) {
        this.tblingresos = tblingresos;
    }




}


