package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tbltipoegreso generated by hbm2java
 */
public class Tbltipoegreso  implements java.io.Serializable {
    private static final long serialVersionUID = -1510651236297928723L;


     private Integer sectipoingreso;
     private String conceptoEgreso;
     private Set<Tblegreso> tblegresos = new HashSet<Tblegreso>(0);

    public Tbltipoegreso() {
    }

	
    public Tbltipoegreso(String conceptoEgreso) {
        this.conceptoEgreso = conceptoEgreso;
    }
    public Tbltipoegreso(String conceptoEgreso, Set<Tblegreso> tblegresos) {
       this.conceptoEgreso = conceptoEgreso;
       this.tblegresos = tblegresos;
    }
   
    public Integer getSectipoingreso() {
        return this.sectipoingreso;
    }
    
    public void setSectipoingreso(Integer sectipoingreso) {
        this.sectipoingreso = sectipoingreso;
    }
    public String getConceptoEgreso() {
        return this.conceptoEgreso;
    }
    
    public void setConceptoEgreso(String conceptoEgreso) {
        this.conceptoEgreso = conceptoEgreso;
    }
    public Set<Tblegreso> getTblegresos() {
        return this.tblegresos;
    }
    
    public void setTblegresos(Set<Tblegreso> tblegresos) {
        this.tblegresos = tblegresos;
    }




}


