package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblunidad generated by hbm2java
 */
public class Tblunidad  implements java.io.Serializable {
    private static final long serialVersionUID = 8321318104720643932L;


     private Integer secunidad;
     private String unidades;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Tblunidad() {
    }

	
    public Tblunidad(String unidades) {
        this.unidades = unidades;
    }
    public Tblunidad(String unidades, Set<Producto> productos) {
       this.unidades = unidades;
       this.productos = productos;
    }
   
    public Integer getSecunidad() {
        return this.secunidad;
    }
    
    public void setSecunidad(Integer secunidad) {
        this.secunidad = secunidad;
    }
    public String getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(String unidades) {
        this.unidades = unidades;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


