package com.pasantia.entidades;
// Generated 10/09/2013 10:40:59 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblunidad generated by hbm2java
 */
@Entity
@Table(name="tblunidad"
    ,catalog="CasinoPasantia"
)
public class Tblunidad  implements java.io.Serializable {


     private Integer secunidad;
     private String unidades;
     private Set productos = new HashSet(0);

    public Tblunidad() {
    }

	
    public Tblunidad(String unidades) {
        this.unidades = unidades;
    }
    public Tblunidad(String unidades, Set productos) {
       this.unidades = unidades;
       this.productos = productos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECUNIDAD", unique=true, nullable=false)
    public Integer getSecunidad() {
        return this.secunidad;
    }
    
    public void setSecunidad(Integer secunidad) {
        this.secunidad = secunidad;
    }
    
    @Column(name="UNIDADES", nullable=false, length=45)
    public String getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(String unidades) {
        this.unidades = unidades;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblunidad")
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


