package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblventa generated by hbm2java
 */
public class Tblventa  implements java.io.Serializable {
    private static final long serialVersionUID = 2768652900528552645L;


     private Integer secventa;
     private Persona personaBySeccliente;
     private Persona personaBySecvendedor;
     private Casino casino;
     private TblformaPago tblformaPago;
     private Date fecha;
     private String observacion;
     private Long total;
     private Byte totalCantidad;
     private Set<Tblingreso> tblingresos = new HashSet<Tblingreso>(0);
     private Set<TbldetalleVenta> tbldetalleVentas = new HashSet<TbldetalleVenta>(0);

    public Tblventa() {
    }

	
    public Tblventa(Persona personaBySeccliente, Persona personaBySecvendedor, Casino casino, TblformaPago tblformaPago, Date fecha) {
        this.personaBySeccliente = personaBySeccliente;
        this.personaBySecvendedor = personaBySecvendedor;
        this.casino = casino;
        this.tblformaPago = tblformaPago;
        this.fecha = fecha;
    }
    public Tblventa(Persona personaBySeccliente, Persona personaBySecvendedor, Casino casino, TblformaPago tblformaPago, Date fecha, String observacion, Long total, Byte totalCantidad, Set<Tblingreso> tblingresos, Set<TbldetalleVenta> tbldetalleVentas) {
       this.personaBySeccliente = personaBySeccliente;
       this.personaBySecvendedor = personaBySecvendedor;
       this.casino = casino;
       this.tblformaPago = tblformaPago;
       this.fecha = fecha;
       this.observacion = observacion;
       this.total = total;
       this.totalCantidad = totalCantidad;
       this.tblingresos = tblingresos;
       this.tbldetalleVentas = tbldetalleVentas;
    }
   
    public Integer getSecventa() {
        return this.secventa;
    }
    
    public void setSecventa(Integer secventa) {
        this.secventa = secventa;
    }
    public Persona getPersonaBySeccliente() {
        return this.personaBySeccliente;
    }
    
    public void setPersonaBySeccliente(Persona personaBySeccliente) {
        this.personaBySeccliente = personaBySeccliente;
    }
    public Persona getPersonaBySecvendedor() {
        return this.personaBySecvendedor;
    }
    
    public void setPersonaBySecvendedor(Persona personaBySecvendedor) {
        this.personaBySecvendedor = personaBySecvendedor;
    }
    public Casino getCasino() {
        return this.casino;
    }
    
    public void setCasino(Casino casino) {
        this.casino = casino;
    }
    public TblformaPago getTblformaPago() {
        return this.tblformaPago;
    }
    
    public void setTblformaPago(TblformaPago tblformaPago) {
        this.tblformaPago = tblformaPago;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Long getTotal() {
        return this.total;
    }
    
    public void setTotal(Long total) {
        this.total = total;
    }
    public Byte getTotalCantidad() {
        return this.totalCantidad;
    }
    
    public void setTotalCantidad(Byte totalCantidad) {
        this.totalCantidad = totalCantidad;
    }
    public Set<Tblingreso> getTblingresos() {
        return this.tblingresos;
    }
    
    public void setTblingresos(Set<Tblingreso> tblingresos) {
        this.tblingresos = tblingresos;
    }
    public Set<TbldetalleVenta> getTbldetalleVentas() {
        return this.tbldetalleVentas;
    }
    
    public void setTbldetalleVentas(Set<TbldetalleVenta> tbldetalleVentas) {
        this.tbldetalleVentas = tbldetalleVentas;
    }




}


