package com.pasantia.entidades;
// Generated 10/09/2013 10:40:59 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblventa generated by hbm2java
 */
@Entity
@Table(name="TBLVENTA"
    ,catalog="CasinoPasantia"
)
public class Tblventa  implements java.io.Serializable {


     private Integer secventa;
     private Persona personaBySeccliente;
     private Persona personaBySecvendedor;
     private Casino casino;
     private TblformaPago tblformaPago;
     private Date fecha;
     private String observacion;
     private Byte total;
     private Byte totalCantidad;
     private Set tblingresos = new HashSet(0);
     private Set tbldetalleVentas = new HashSet(0);

    public Tblventa() {
    }

	
    public Tblventa(Persona personaBySeccliente, Persona personaBySecvendedor, Casino casino, TblformaPago tblformaPago, Date fecha) {
        this.personaBySeccliente = personaBySeccliente;
        this.personaBySecvendedor = personaBySecvendedor;
        this.casino = casino;
        this.tblformaPago = tblformaPago;
        this.fecha = fecha;
    }
    public Tblventa(Persona personaBySeccliente, Persona personaBySecvendedor, Casino casino, TblformaPago tblformaPago, Date fecha, String observacion, Byte total, Byte totalCantidad, Set tblingresos, Set tbldetalleVentas) {
       this.personaBySeccliente = personaBySeccliente;
       this.personaBySecvendedor = personaBySecvendedor;
       this.casino = casino;
       this.tblformaPago = tblformaPago;
       this.fecha = fecha;
       this.observacion = observacion;
       this.total = total;
       this.totalCantidad = totalCantidad;
       this.tblingresos = tblingresos;
       this.tbldetalleVentas = tbldetalleVentas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECVENTA", unique=true, nullable=false)
    public Integer getSecventa() {
        return this.secventa;
    }
    
    public void setSecventa(Integer secventa) {
        this.secventa = secventa;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECCLIENTE", nullable=false)
    public Persona getPersonaBySeccliente() {
        return this.personaBySeccliente;
    }
    
    public void setPersonaBySeccliente(Persona personaBySeccliente) {
        this.personaBySeccliente = personaBySeccliente;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECVENDEDOR", nullable=false)
    public Persona getPersonaBySecvendedor() {
        return this.personaBySecvendedor;
    }
    
    public void setPersonaBySecvendedor(Persona personaBySecvendedor) {
        this.personaBySecvendedor = personaBySecvendedor;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECCASINO", nullable=false)
    public Casino getCasino() {
        return this.casino;
    }
    
    public void setCasino(Casino casino) {
        this.casino = casino;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECFORMAPAGO", nullable=false)
    public TblformaPago getTblformaPago() {
        return this.tblformaPago;
    }
    
    public void setTblformaPago(TblformaPago tblformaPago) {
        this.tblformaPago = tblformaPago;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHA", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="OBSERVACION", length=45)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    
    @Column(name="TOTAL", precision=2, scale=0)
    public Byte getTotal() {
        return this.total;
    }
    
    public void setTotal(Byte total) {
        this.total = total;
    }
    
    @Column(name="TOTAL_CANTIDAD", precision=2, scale=0)
    public Byte getTotalCantidad() {
        return this.totalCantidad;
    }
    
    public void setTotalCantidad(Byte totalCantidad) {
        this.totalCantidad = totalCantidad;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblventa")
    public Set getTblingresos() {
        return this.tblingresos;
    }
    
    public void setTblingresos(Set tblingresos) {
        this.tblingresos = tblingresos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblventa")
    public Set getTbldetalleVentas() {
        return this.tbldetalleVentas;
    }
    
    public void setTbldetalleVentas(Set tbldetalleVentas) {
        this.tbldetalleVentas = tbldetalleVentas;
    }




}


