package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA



/**
 * Tblvisitapedidos generated by hbm2java
 */
public class Tblvisitapedidos  implements java.io.Serializable {
    private static final long serialVersionUID = 3313258439357524005L;


     private Integer secvisitapedidos;
     private Tblproveedor tblproveedor;
     private Boolean lunes;
     private Boolean martes;
     private Boolean miercoles;
     private Boolean jueves;
     private Boolean viernes;
     private Boolean sabado;
     private Boolean domingo;

    public Tblvisitapedidos() {
    }

	
    public Tblvisitapedidos(Tblproveedor tblproveedor) {
        this.tblproveedor = tblproveedor;
    }
    public Tblvisitapedidos(Tblproveedor tblproveedor, Boolean lunes, Boolean martes, Boolean miercoles, Boolean jueves, Boolean viernes, Boolean sabado, Boolean domingo) {
       this.tblproveedor = tblproveedor;
       this.lunes = lunes;
       this.martes = martes;
       this.miercoles = miercoles;
       this.jueves = jueves;
       this.viernes = viernes;
       this.sabado = sabado;
       this.domingo = domingo;
    }
   
    public Integer getSecvisitapedidos() {
        return this.secvisitapedidos;
    }
    
    public void setSecvisitapedidos(Integer secvisitapedidos) {
        this.secvisitapedidos = secvisitapedidos;
    }
    public Tblproveedor getTblproveedor() {
        return this.tblproveedor;
    }
    
    public void setTblproveedor(Tblproveedor tblproveedor) {
        this.tblproveedor = tblproveedor;
    }
    public Boolean getLunes() {
        return this.lunes;
    }
    
    public void setLunes(Boolean lunes) {
        this.lunes = lunes;
    }
    public Boolean getMartes() {
        return this.martes;
    }
    
    public void setMartes(Boolean martes) {
        this.martes = martes;
    }
    public Boolean getMiercoles() {
        return this.miercoles;
    }
    
    public void setMiercoles(Boolean miercoles) {
        this.miercoles = miercoles;
    }
    public Boolean getJueves() {
        return this.jueves;
    }
    
    public void setJueves(Boolean jueves) {
        this.jueves = jueves;
    }
    public Boolean getViernes() {
        return this.viernes;
    }
    
    public void setViernes(Boolean viernes) {
        this.viernes = viernes;
    }
    public Boolean getSabado() {
        return this.sabado;
    }
    
    public void setSabado(Boolean sabado) {
        this.sabado = sabado;
    }
    public Boolean getDomingo() {
        return this.domingo;
    }
    
    public void setDomingo(Boolean domingo) {
        this.domingo = domingo;
    }




}


