package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoIdentificacion generated by hbm2java
 */
public class TipoIdentificacion  implements java.io.Serializable {
    private static final long serialVersionUID = -2831143606908074435L;


     private Integer idTipoIdentificacion;
     private String nombreTipoIdentificacion;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public TipoIdentificacion() {
    }

	
    public TipoIdentificacion(String nombreTipoIdentificacion) {
        this.nombreTipoIdentificacion = nombreTipoIdentificacion;
    }
    public TipoIdentificacion(String nombreTipoIdentificacion, Set<Persona> personas) {
       this.nombreTipoIdentificacion = nombreTipoIdentificacion;
       this.personas = personas;
    }
   
    public Integer getIdTipoIdentificacion() {
        return this.idTipoIdentificacion;
    }
    
    public void setIdTipoIdentificacion(Integer idTipoIdentificacion) {
        this.idTipoIdentificacion = idTipoIdentificacion;
    }
    public String getNombreTipoIdentificacion() {
        return this.nombreTipoIdentificacion;
    }
    
    public void setNombreTipoIdentificacion(String nombreTipoIdentificacion) {
        this.nombreTipoIdentificacion = nombreTipoIdentificacion;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


