package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoPersona generated by hbm2java
 */
public class TipoPersona  implements java.io.Serializable {
    private static final long serialVersionUID = 503663057181793167L;


     private Integer idTipoPersona;
     private String nombreTipoPersona;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public TipoPersona() {
    }

	
    public TipoPersona(String nombreTipoPersona) {
        this.nombreTipoPersona = nombreTipoPersona;
    }
    public TipoPersona(String nombreTipoPersona, Set<Persona> personas) {
       this.nombreTipoPersona = nombreTipoPersona;
       this.personas = personas;
    }
   
    public Integer getIdTipoPersona() {
        return this.idTipoPersona;
    }
    
    public void setIdTipoPersona(Integer idTipoPersona) {
        this.idTipoPersona = idTipoPersona;
    }
    public String getNombreTipoPersona() {
        return this.nombreTipoPersona;
    }
    
    public void setNombreTipoPersona(String nombreTipoPersona) {
        this.nombreTipoPersona = nombreTipoPersona;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


