package com.pasantia.entidades;
// Generated 6/10/2013 04:27:25 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPersona generated by hbm2java
 */
@Entity
@Table(name="Tipo_Persona"
    ,catalog="CasinoPasantia"
)
public class TipoPersona  implements java.io.Serializable {


     private Integer idTipoPersona;
     private String nombreTipoPersona;
     private Set personas = new HashSet(0);

    public TipoPersona() {
    }

	
    public TipoPersona(String nombreTipoPersona) {
        this.nombreTipoPersona = nombreTipoPersona;
    }
    public TipoPersona(String nombreTipoPersona, Set personas) {
       this.nombreTipoPersona = nombreTipoPersona;
       this.personas = personas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idTipo_Persona", unique=true, nullable=false)
    public Integer getIdTipoPersona() {
        return this.idTipoPersona;
    }
    
    public void setIdTipoPersona(Integer idTipoPersona) {
        this.idTipoPersona = idTipoPersona;
    }
    
    @Column(name="nombre_tipo_persona", nullable=false, length=45)
    public String getNombreTipoPersona() {
        return this.nombreTipoPersona;
    }
    
    public void setNombreTipoPersona(String nombreTipoPersona) {
        this.nombreTipoPersona = nombreTipoPersona;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tipoPersona")
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


