package com.pasantia.entidades;
// Generated 10/09/2013 10:40:59 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="Usuario"
    ,catalog="CasinoPasantia"
)
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Persona persona;
     private Rol rol;
     private String clave;
     private String nomusuario;
     private boolean activo;
     private String sesion;

    public Usuario() {
    }

    public Usuario(Persona persona, Rol rol, String clave, String nomusuario, boolean activo, String sesion) {
       this.persona = persona;
       this.rol = rol;
       this.clave = clave;
       this.nomusuario = nomusuario;
       this.activo = activo;
       this.sesion = sesion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idUsuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="secpersona", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="secrol", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    
    @Column(name="clave", nullable=false, length=45)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    
    @Column(name="nomusuario", nullable=false, length=45)
    public String getNomusuario() {
        return this.nomusuario;
    }
    
    public void setNomusuario(String nomusuario) {
        this.nomusuario = nomusuario;
    }
    
    @Column(name="activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    
    @Column(name="sesion", nullable=false, length=45)
    public String getSesion() {
        return this.sesion;
    }
    
    public void setSesion(String sesion) {
        this.sesion = sesion;
    }




}


