package com.pasantia.entidades;
// Generated 6/10/2013 01:37:53 PM by Hibernate Tools 3.2.1.GA



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {
    private static final long serialVersionUID = 7470565290181221670L;


     private Integer idUsuario;
     private Persona persona;
     private Rol rol;
     private String clave;
     private String nomusuario;
     private boolean activo;
     private boolean sesion;
     private String thema;

    public Usuario() {
    }

    public Usuario(Persona persona, Rol rol, String clave, String nomusuario, boolean activo, boolean sesion, String thema) {
       this.persona = persona;
       this.rol = rol;
       this.clave = clave;
       this.nomusuario = nomusuario;
       this.activo = activo;
       this.sesion = sesion;
       this.thema = thema;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getNomusuario() {
        return this.nomusuario;
    }
    
    public void setNomusuario(String nomusuario) {
        this.nomusuario = nomusuario;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public boolean isSesion() {
        return this.sesion;
    }
    
    public void setSesion(boolean sesion) {
        this.sesion = sesion;
    }
    public String getThema() {
        return this.thema;
    }
    
    public void setThema(String thema) {
        this.thema = thema;
    }




}


