package com.pasantia.entidades;
// Generated 17/08/2013 10:58:34 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(name="Venta"
    ,catalog="CasinoPasantia"
)
public class Venta  implements java.io.Serializable {


     private Integer idVenta;
     private DetalleVenta detalleVenta;
     private Persona persona;
     private Date fechaVenta;

    public Venta() {
    }

    public Venta(DetalleVenta detalleVenta, Persona persona, Date fechaVenta) {
       this.detalleVenta = detalleVenta;
       this.persona = persona;
       this.fechaVenta = fechaVenta;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idVenta", unique=true, nullable=false)
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_detalle_venta", nullable=false)
    public DetalleVenta getDetalleVenta() {
        return this.detalleVenta;
    }
    
    public void setDetalleVenta(DetalleVenta detalleVenta) {
        this.detalleVenta = detalleVenta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_persona", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_venta", nullable=false, length=19)
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }




}


